// AUTO-GENERATED by tools/generate-prod-master-data.py — do not hand-edit.
// Source: the customer's Excel master-data delivery. Regenerate with:
//   python3 tools/generate-prod-master-data.py <Import data form.xlsx>
export interface ProdStaffSeed { username: string; employeeCode: string; fullName: string; roleCode: string | null; roleGroup: string | null; }
export interface ProdDriverSeed { code: string; username: string; name: string; idNumber: string | null; licenseNumber: string | null; licenseExpiryDate: string | null; phone: string | null; bankName: string | null; bankAccount: string | null; salaryType: string | null; }
export interface ProdCustomerSeed { name: string; shortName: string | null; code: string; taxCode: string | null; address: string | null; director: string | null; directorPhone: string | null; accountantName: string | null; accountantPhone: string | null; email: string | null; paymentTermChiHoDays: number | null; paymentTermCuocDays: number | null; }
export interface ProdSiteSeed { name: string; code: string; shortName: string | null; customerCode: string | null; routeName: string | null; address: string | null; note: string | null; contactName: string | null; contactPhone: string | null; warehouseContactInfo: string | null; liftInfo: string | null; dropInfo: string | null; cleaningInfo: string | null; mapsUrl: string | null; }
// name = sheet column "Tên tuyến" (full name) — the seeded DB `name`;
// shortName = "Tên tuyến rút gọn". Do not split Tên tuyến into a separate
// unused field: seed-prod persists `name` verbatim.
export interface ProdRouteSeed { name: string; code: string; shortName: string; loadPoint: string | null; distanceKm: number | null; tolls: number | null; note: string | null; }
export interface ProdTractorSeed { plate: string; driverName: string | null; vehicleClass: string | null; brand: string | null; towCapacityTons: number | null; fuelLPer100kmLoaded: number | null; fuelLPer100kmEmpty: number | null; inspectionDeadline: string | null; insuranceExpiry: string | null; preferredRoute: string | null; note: string | null; }
export interface ProdTrailerSeed { plate: string; pairedTractor: string | null; type: string | null; maxPayloadTons: number | null; maxAxleLoadFrontTons: number | null; maxAxleLoadRearTons: number | null; inspectionDeadline: string | null; note: string | null; }
export interface ProdPortSeed { name: string; code: string | null; classification: string | null; legalEntity: string | null; address: string | null; isLachHuyen: boolean; opsPortalUrl: string | null; position: string | null; }
export interface ProdCarrierSeed { name: string; shortName: string; taxCode: string | null; address: string | null; contactPerson: string | null; phone: string | null; }

export const prodStaff: ProdStaffSeed[] = [
  {
    "username": "phuongnt",
    "employeeCode": "NV001",
    "fullName": "Nguyễn Thị Phương",
    "roleCode": "R_ADMIN",
    "roleGroup": "Ban Giám Đốc"
  },
  {
    "username": "namnv",
    "employeeCode": "NV002",
    "fullName": "Nguyễn Văn Nam",
    "roleCode": "R_ADMIN",
    "roleGroup": "Ban Giám Đốc"
  },
  {
    "username": "hoangnh",
    "employeeCode": "NV003",
    "fullName": "Nguyễn Huy Hoàng",
    "roleCode": "R_OPS",
    "roleGroup": "Ops"
  },
  {
    "username": "hungld",
    "employeeCode": "NV004",
    "fullName": "Lưu Danh Hùng",
    "roleCode": "R_OPS",
    "roleGroup": "Ops"
  },
  {
    "username": "duongtt",
    "employeeCode": "NV005",
    "fullName": "Trần Thiên Dương",
    "roleCode": "R_OPS",
    "roleGroup": "Ops"
  },
  {
    "username": "tuvn",
    "employeeCode": "NV006",
    "fullName": "Vũ Ngọc Tú",
    "roleCode": "R_OPS",
    "roleGroup": "Ops"
  },
  {
    "username": "hoangnm",
    "employeeCode": "NV007",
    "fullName": "Nguyễn Minh Hoàng",
    "roleCode": "R_OPS",
    "roleGroup": "Ops"
  },
  {
    "username": "cuongvd",
    "employeeCode": "NV008",
    "fullName": "Vũ Đình Cường",
    "roleCode": "R_OPS",
    "roleGroup": "Ops"
  },
  {
    "username": "hoapt",
    "employeeCode": "NV009",
    "fullName": "Phạm Thị Hòa",
    "roleCode": "R_ACC",
    "roleGroup": "Kế toán"
  },
  {
    "username": "liennt",
    "employeeCode": "NV010",
    "fullName": "Nguyễn Thị Liên",
    "roleCode": "R_ACC",
    "roleGroup": "Kế toán"
  },
  {
    "username": "lydp",
    "employeeCode": "NV011",
    "fullName": "Đoàn Phương Ly",
    "roleCode": "R_ACC",
    "roleGroup": "Kế toán"
  },
  {
    "username": "vanntt",
    "employeeCode": "NV012",
    "fullName": "Nguyễn Thị Thảo Vân",
    "roleCode": "R_ACC",
    "roleGroup": "Kế toán"
  },
  {
    "username": "myvtt",
    "employeeCode": "NV013",
    "fullName": "Vũ Thị Trà My",
    "roleCode": "R_ACC",
    "roleGroup": "Kế toán"
  },
  {
    "username": "ngocntm",
    "employeeCode": "NV014",
    "fullName": "Nguyễn Thị Minh Ngọc",
    "roleCode": "R_ACC",
    "roleGroup": "Kế toán"
  },
  {
    "username": "dungnv",
    "employeeCode": "NV015",
    "fullName": "Nguyễn Văn Dũng",
    "roleCode": "R_DIS",
    "roleGroup": "Điều vận"
  },
  {
    "username": "bacdk",
    "employeeCode": "NV016",
    "fullName": "Đỗ Khoan Bắc",
    "roleCode": "R_DIS",
    "roleGroup": "Điều vận"
  },
  {
    "username": "huongnt",
    "employeeCode": "NV017",
    "fullName": "Nguyễn Thị Hương",
    "roleCode": "R_DIS",
    "roleGroup": "Điều vận"
  },
  {
    "username": "thanhdc",
    "employeeCode": "NV018",
    "fullName": "Đinh Công Thành",
    "roleCode": "R_CUS",
    "roleGroup": "Cus"
  },
  {
    "username": "tiepvv",
    "employeeCode": "NV019",
    "fullName": "Vũ Văn Tiệp",
    "roleCode": "R_CUS",
    "roleGroup": "Cus"
  },
  {
    "username": "anhdtv",
    "employeeCode": "NV020",
    "fullName": "Đặng Thị Vân Anh",
    "roleCode": "R_CUS",
    "roleGroup": "Cus"
  },
  {
    "username": "huyenntt",
    "employeeCode": "NV021",
    "fullName": "Nguyễn Thị Thanh Huyền",
    "roleCode": "R_CUS",
    "roleGroup": "Cus"
  },
  {
    "username": "anhntn",
    "employeeCode": "NV022",
    "fullName": "Nguyễn Thị Ngọc Ánh",
    "roleCode": "R_CUS",
    "roleGroup": "Cus"
  }
];

export const prodDrivers: ProdDriverSeed[] = [
  {
    "code": "LVLONG",
    "username": "lvlong",
    "name": "Lương Văn Long",
    "idNumber": "038092001476",
    "licenseNumber": "380141031128",
    "licenseExpiryDate": null,
    "phone": "0988822579",
    "bankName": "Công Thương Việt Nam (VIETINBANK)",
    "bankAccount": "100800882279",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "NVTHO",
    "username": "nvtho",
    "name": "Nguyễn Văn Thọ",
    "idNumber": "030091007470",
    "licenseNumber": "270161004362",
    "licenseExpiryDate": null,
    "phone": "0975289181",
    "bankName": "Ngoại thương Việt Nam (VCB)",
    "bankAccount": "0351000894686",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "NDTUAN",
    "username": "ndtuan",
    "name": "Nguyễn Duy Tuấn",
    "idNumber": "025093009151",
    "licenseNumber": "10166066051",
    "licenseExpiryDate": null,
    "phone": "0979697258",
    "bankName": "Quân đội (MB)",
    "bankAccount": "3540107506007",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "NTVU",
    "username": "ntvu",
    "name": "Nguyễn Thế Vũ",
    "idNumber": "031088001164",
    "licenseNumber": "310186015098",
    "licenseExpiryDate": null,
    "phone": "0334751677",
    "bankName": "Ngoại thương Việt Nam (VCB)",
    "bankAccount": "1048253879",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "NHVUONG",
    "username": "nhvuong",
    "name": "Nguyễn Huy Vương",
    "idNumber": "030084005894",
    "licenseNumber": "300098301282",
    "licenseExpiryDate": null,
    "phone": "0984963484",
    "bankName": "Ngoại thương Việt Nam (VCB)",
    "bankAccount": "1043565309",
    "salaryType": "LƯƠNG CHUYẾN"
  },
  {
    "code": "BVAN",
    "username": "bvan",
    "name": "Bùi Văn An",
    "idNumber": "030084011951",
    "licenseNumber": "270137014261",
    "licenseExpiryDate": null,
    "phone": "0961250628",
    "bankName": "Ngoại thương Việt Nam (VCB)",
    "bankAccount": "0341006964468",
    "salaryType": "LƯƠNG CHUYẾN"
  },
  {
    "code": "DVTHUC",
    "username": "dvthuc",
    "name": "Dương Văn Thực",
    "idNumber": "024085007906",
    "licenseNumber": "270149001932",
    "licenseExpiryDate": null,
    "phone": "0985246985",
    "bankName": "Tiên Phong (TPB)",
    "bankAccount": "00000813397",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "PNVAN",
    "username": "pnvan",
    "name": "Phạm Ngọc Văn",
    "idNumber": "015097002811",
    "licenseNumber": "150189005252",
    "licenseExpiryDate": null,
    "phone": "0336170697",
    "bankName": "Quân đội (MB)",
    "bankAccount": "0336170697",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "DTTHINH",
    "username": "dtthinh",
    "name": "Đinh Thanh Thịnh",
    "idNumber": "025090001409",
    "licenseNumber": "250161000025",
    "licenseExpiryDate": null,
    "phone": "0973768118",
    "bankName": "Quân đội (MB)",
    "bankAccount": "6666118906666",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "BVHAU",
    "username": "bvhau",
    "name": "Bùi Văn Hậu",
    "idNumber": "038091015152",
    "licenseNumber": "380138017483",
    "licenseExpiryDate": null,
    "phone": "0367873329",
    "bankName": "Ngoại thương Việt Nam (VCB)",
    "bankAccount": "1024754965",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "BQHUONG",
    "username": "bqhuong",
    "name": "Bùi Quang Hường",
    "idNumber": "030090011211",
    "licenseNumber": "310125004211",
    "licenseExpiryDate": null,
    "phone": "0987278910",
    "bankName": "Quân đội (MB)",
    "bankAccount": "0987278910",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "HTHUNG",
    "username": "hthung",
    "name": "Hoàng Trọng Hùng",
    "idNumber": "025094010778",
    "licenseNumber": "250199005197",
    "licenseExpiryDate": null,
    "phone": "0966341815",
    "bankName": "Ngoại thương Việt Nam (VCB)",
    "bankAccount": "0351001041356",
    "salaryType": "LƯƠNG CHUYẾN"
  },
  {
    "code": "VVTRUNG",
    "username": "vvtrung",
    "name": "Vũ Văn Trung",
    "idNumber": "027087009767",
    "licenseNumber": "270148002129",
    "licenseExpiryDate": null,
    "phone": "0981309345",
    "bankName": "Ngoại thương Việt Nam (VCB)",
    "bankAccount": "0351001228809",
    "salaryType": "LƯƠNG CHUYẾN"
  },
  {
    "code": "NVDUONG",
    "username": "nvduong",
    "name": "Nguyễn Văn Dương",
    "idNumber": "030084002733",
    "licenseNumber": "300116302169",
    "licenseExpiryDate": null,
    "phone": "0977094284",
    "bankName": "Ngoại thương Việt Nam (VCB)",
    "bankAccount": "0541000186578",
    "salaryType": "LƯƠNG CHUYẾN"
  },
  {
    "code": "TTHIEU",
    "username": "tthieu",
    "name": "Trần Trung Hiếu",
    "idNumber": "034085020347",
    "licenseNumber": "340114344653",
    "licenseExpiryDate": null,
    "phone": "0964496330",
    "bankName": "Công Thương Việt Nam (VIETINBANK)",
    "bankAccount": "100879528403",
    "salaryType": "LƯƠNG CHUYẾN"
  },
  {
    "code": "BTDUNG",
    "username": "btdung",
    "name": "Bùi Tiến Dũng",
    "idNumber": "017084004899",
    "licenseNumber": "170129000495",
    "licenseExpiryDate": null,
    "phone": "0986342975",
    "bankName": "Hàng hải (MSB)",
    "bankAccount": "8606101984",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "LVTUYEN",
    "username": "lvtuyen",
    "name": "Lưu Văn Tuyền",
    "idNumber": "030084002127",
    "licenseNumber": "300081304977",
    "licenseExpiryDate": null,
    "phone": "0974847679",
    "bankName": "Ngoại thương Việt Nam (VCB)",
    "bankAccount": "1002056789",
    "salaryType": "LƯƠNG CHUYẾN"
  },
  {
    "code": "NVDUNG",
    "username": "nvdung",
    "name": "Nguyễn Văn Dũng",
    "idNumber": "027083019159",
    "licenseNumber": "270119271431",
    "licenseExpiryDate": null,
    "phone": "0362157612",
    "bankName": "Công Thương Việt Nam (VIETINBANK)",
    "bankAccount": "109873767998",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "LVLO",
    "username": "lvlo",
    "name": "Lục Văn Lô",
    "idNumber": "024091017708",
    "licenseNumber": "240139011034",
    "licenseExpiryDate": null,
    "phone": "0339224168",
    "bankName": "Công Thương Việt Nam (VIETINBANK)",
    "bankAccount": "106866946004",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "PTSON",
    "username": "ptson",
    "name": "Phạm Thanh Sơn",
    "idNumber": "030085025100",
    "licenseNumber": "300119303576",
    "licenseExpiryDate": null,
    "phone": "0978257219",
    "bankName": "Quân đội (MB)",
    "bankAccount": "0978257219",
    "salaryType": "LƯƠNG CHUYẾN"
  },
  {
    "code": "PVTRUONG",
    "username": "pvtruong",
    "name": "Phan Văn Trường",
    "idNumber": "027083015590",
    "licenseNumber": "790138028378",
    "licenseExpiryDate": null,
    "phone": "0988786345",
    "bankName": "Công Thương Việt Nam (VIETINBANK)",
    "bankAccount": "101870115196",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "LNLONG",
    "username": "lnlong",
    "name": "Lê Ngọc Long",
    "idNumber": "030090009661",
    "licenseNumber": "270125110290",
    "licenseExpiryDate": null,
    "phone": "0988481519",
    "bankName": "Ngoại thương Việt Nam (VCB)",
    "bankAccount": "1017226171",
    "salaryType": "LƯƠNG CHUYẾN"
  },
  {
    "code": "TVTHANG",
    "username": "tvthang",
    "name": "Trần Văn Thắng",
    "idNumber": "030080002683",
    "licenseNumber": "300025300656",
    "licenseExpiryDate": null,
    "phone": "0985873114",
    "bankName": "Hàng hải (MSB)",
    "bankAccount": "02001018550873",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "VVCHINH",
    "username": "vvchinh",
    "name": "Vũ Văn Chính",
    "idNumber": "027078006674",
    "licenseNumber": "790111224384",
    "licenseExpiryDate": null,
    "phone": "0917977922",
    "bankName": "Quân đội (MB)",
    "bankAccount": "0917977922",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "NVQUYNH",
    "username": "nvquynh",
    "name": "Nguyễn Văn Quỳnh",
    "idNumber": "031081022033",
    "licenseNumber": "220107003531",
    "licenseExpiryDate": null,
    "phone": "0967603996",
    "bankName": "Quân đội (MB)",
    "bankAccount": "0989215833",
    "salaryType": "LƯƠNG CHUYẾN"
  },
  {
    "code": "LQTUYEN",
    "username": "lqtuyen",
    "name": "Lê Quang Tuyền",
    "idNumber": "027092012146",
    "licenseNumber": "270196009209",
    "licenseExpiryDate": null,
    "phone": "0326059129",
    "bankName": "Hàng hải (MSB)",
    "bankAccount": "80000016796",
    "salaryType": "LƯƠNG CHUYẾN"
  },
  {
    "code": "TTQUAN",
    "username": "ttquan",
    "name": "Trần Thế Quân",
    "idNumber": "030091003096",
    "licenseNumber": "310182000748",
    "licenseExpiryDate": null,
    "phone": "0982165163",
    "bankName": "Kỹ Thương (TCB)",
    "bankAccount": "2979686869",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "BVKIEM",
    "username": "bvkiem",
    "name": "Bùi Văn Kiệm",
    "idNumber": "030085020425",
    "licenseNumber": "300071300918",
    "licenseExpiryDate": null,
    "phone": "0989112123",
    "bankName": "Quân đội (MB)",
    "bankAccount": "0989112123",
    "salaryType": "LƯƠNG CHUYẾN"
  },
  {
    "code": "TVTHAM",
    "username": "tvtham",
    "name": "Tô Viết Thấm",
    "idNumber": "020082009871",
    "licenseNumber": "270146016591",
    "licenseExpiryDate": null,
    "phone": "0982365118",
    "bankName": "Kỹ Thương (TCB)",
    "bankAccount": "881212128888",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "HQTHO",
    "username": "hqtho",
    "name": "Hoàng Quang Thơ",
    "idNumber": "015093006478",
    "licenseNumber": "250143018282",
    "licenseExpiryDate": null,
    "phone": "0332702789",
    "bankName": "Hàng hải (MSB)",
    "bankAccount": "80001251274",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "LVDIEP",
    "username": "lvdiep",
    "name": "Lê Văn Điệp",
    "idNumber": "030088003622",
    "licenseNumber": "300173005304",
    "licenseExpiryDate": null,
    "phone": "0376345569",
    "bankName": "Công Thương Việt Nam (VIETINBANK)",
    "bankAccount": "104582156789",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "LHNAM",
    "username": "lhnam",
    "name": "Lê Hải Nam",
    "idNumber": "030077022437",
    "licenseNumber": "300055301823",
    "licenseExpiryDate": null,
    "phone": "0904609712",
    "bankName": "Đầu tư và phát triển (BIDV)",
    "bankAccount": "46110000370855",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "PVCAN",
    "username": "pvcan",
    "name": "Nguyễn Văn Cần",
    "idNumber": "027085003346",
    "licenseNumber": "270043804260",
    "licenseExpiryDate": null,
    "phone": "0359980666",
    "bankName": "Hàng hải (MSB)",
    "bankAccount": "80000338995",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "PDPHUNG",
    "username": "pdphung",
    "name": "Phùng Đắc Phụng",
    "idNumber": "027088014447",
    "licenseNumber": "270160006143",
    "licenseExpiryDate": null,
    "phone": "0982358657",
    "bankName": "Hàng hải (MSB)",
    "bankAccount": "03101011835094",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "NVHOAN",
    "username": "nvhoan",
    "name": "Nguyễn Văn Hoàn",
    "idNumber": "027088003648",
    "licenseNumber": "270137006440",
    "licenseExpiryDate": null,
    "phone": "0385596865",
    "bankName": "Ngoại thương Việt Nam (VCB)",
    "bankAccount": "1014892282",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "LVKHAI",
    "username": "lvkhai",
    "name": "Lê Văn Khải",
    "idNumber": "038090015135",
    "licenseNumber": "790150085618",
    "licenseExpiryDate": null,
    "phone": "0983162141",
    "bankName": "Ngoại thương Việt Nam (VCB)",
    "bankAccount": "1032921556",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "DVDAI",
    "username": "dvdai",
    "name": "Đinh Văn Đại",
    "idNumber": "025090003558",
    "licenseNumber": "10176103535",
    "licenseExpiryDate": null,
    "phone": "0971063590",
    "bankName": "Quân đội (MB)",
    "bankAccount": "0971063590",
    "salaryType": "LƯƠNG CỨNG"
  },
  {
    "code": "PXHUAN",
    "username": "pxhuan",
    "name": "Phí Xuân Hoàn",
    "idNumber": "025081014378",
    "licenseNumber": "250063006572",
    "licenseExpiryDate": null,
    "phone": "0394812299",
    "bankName": "Sài Gòn Hà Nội (SHB)",
    "bankAccount": "198133683368",
    "salaryType": "LƯƠNG CHUYẾN"
  },
  {
    "code": "TDTRUNG",
    "username": "tdtrung",
    "name": "Trần Đức Trung",
    "idNumber": "034087017977",
    "licenseNumber": "10157045227",
    "licenseExpiryDate": null,
    "phone": "0986378838",
    "bankName": "Kỹ Thương (TCB)",
    "bankAccount": "19030326356015",
    "salaryType": "KHÔNG LƯƠNG"
  }
];

export const prodCustomers: ProdCustomerSeed[] = [
  {
    "name": "CÔNG TY TNHH MỘT THÀNH VIÊN LONG MINH",
    "shortName": "Long Minh",
    "code": "LONGMINH",
    "taxCode": "2300540419",
    "address": "Khu 2, Phường Võ Cường, Tỉnh Bắc Ninh",
    "director": "LƯƠNG VĂN LONG",
    "directorPhone": "0912334455",
    "accountantName": null,
    "accountantPhone": null,
    "email": "longminh.logistic@gmail.com; account1@longminhbn.com.vn",
    "paymentTermChiHoDays": 25,
    "paymentTermCuocDays": 75
  },
  {
    "name": "CÔNG TY TNHH LOGCOM VIỆT NAM",
    "shortName": "LOG COM",
    "code": "LOGCOM",
    "taxCode": "2300975219",
    "address": "Đường Hoàng Hoa Thám, Phường Võ Cường, Tỉnh Bắc Ninh, Việt Nam",
    "director": "LƯƠNG VĂN AN",
    "directorPhone": "0988559068",
    "accountantName": null,
    "accountantPhone": null,
    "email": "longminh.logistic@gmail.com; account1@longminhbn.com.vn",
    "paymentTermChiHoDays": 25,
    "paymentTermCuocDays": 75
  }
];

export const prodSites: ProdSiteSeed[] = [
  {
    "name": "CÔNG TY TNHH NEWEB VIỆT NAM",
    "code": "NEWEB-1",
    "shortName": "NEWEB-1",
    "customerCode": "LOGCOM",
    "routeName": "KCN Đồng Văn III, Ninh Bình",
    "address": "Lô đất CN01, Khu công nghiệp Đồng Văn III, Phường Đồng Văn, Tỉnh Ninh Bình, Việt Nam",
    "note": "\"3. Lưu ý cần chú ý khi đóng/ trả hàng tại nhà máy\n- Lái xe đăng ký bảo vệ vào đóng/ trả cho công ty Long Minh- Trước khi vào đóng/ trả hàng lái xe gọi đúng SĐT\nngười quản lý hàng xuất/nhập trong kho để hướng dẫn vị trí đóng/ trả hàng- Nghiêm cấm hút thuốc trong địa phận công ty\n- Hàng đóng điện tử yêu cầu vỏ đẹp, sàn chắc khỏe, ko thủng rách, dính dầu, nước, không, mù\"",
    "contactName": null,
    "contactPhone": null,
    "warehouseContactInfo": "Mr Ngọc Anh : 0989130345\nMr Đức : 0398960072\nMr Hưng: 0968228796",
    "liftInfo": "0700837869",
    "dropInfo": "0700837869",
    "cleaningInfo": "0700837869",
    "mapsUrl": "https://maps.app.goo.gl/ybazQGNV6aikJm4z8"
  },
  {
    "name": "CÔNG TY TNHH NEWEB VIỆT NAM",
    "code": "NEWEB-2",
    "shortName": "NEWEB-2",
    "customerCode": "LOGCOM",
    "routeName": "KCN Đồng Văn III, Ninh Bình",
    "address": "Một phần lô đất CN12, khu công nghiệp hỗ trợ Đồng Văn III, Phường Tiên Sơn, tỉnh Ninh Bình, Việt Nam",
    "note": "\"3. Lưu ý cần chú ý khi đóng/ trả hàng tại nhà máy\n- Lái xe đăng ký bảo vệ vào đóng/ trả cho công ty Long Minh- Trước khi vào đóng/ trả hàng lái xe gọi đúng SĐT\nngười quản lý hàng xuất/nhập trong kho để hướng dẫn vị trí đóng/ trả hàng- Nghiêm cấm hút thuốc trong địa phận công ty\n- Hàng đóng điện tử yêu cầu vỏ đẹp, sàn chắc khỏe, ko thủng rách, dính dầu, nước, không, mù\"",
    "contactName": null,
    "contactPhone": null,
    "warehouseContactInfo": "白班 --- CA NGÀY\n娴妙 : 0968960376\n阿广: 0369860602（优先打这个）-- ƯU TIÊN GỌI SỐ NÀY \n晚班--- CA ĐÊM\n阿兵 : 0984259759",
    "liftInfo": "0700837869",
    "dropInfo": "0700837869",
    "cleaningInfo": "0700837869",
    "mapsUrl": "https://maps.app.goo.gl/36mrLqTitnj1i6Cu5"
  },
  {
    "name": "CÔNG TY TNHH NEWEB VIỆT NAM",
    "code": "NEWEB-3",
    "shortName": "NEWEB-3",
    "customerCode": "LOGCOM",
    "routeName": "KCN Đồng Văn I, Ninh Bình",
    "address": "Khu Công Nghiệp Đồng Văn I Mở Rộng , Phường Đồng Văn, Tỉnh Ninh Bình, Việt Nam",
    "note": "\"3. Lưu ý cần chú ý khi đóng/ trả hàng tại nhà máy\n- Lái xe đăng ký bảo vệ vào đóng/ trả cho công ty Long Minh- Trước khi vào đóng/ trả hàng lái xe gọi đúng SĐT\nngười quản lý hàng xuất/nhập trong kho để hướng dẫn vị trí đóng/ trả hàng- Nghiêm cấm hút thuốc trong địa phận công ty\n- Hàng đóng điện tử yêu cầu vỏ đẹp, sàn chắc khỏe, ko thủng rách, dính dầu, nước, không, mù\"",
    "contactName": null,
    "contactPhone": null,
    "warehouseContactInfo": "ANH CƯƠNG : 0971560672\nANH ĐOÀN : 0367150368",
    "liftInfo": "0700837869",
    "dropInfo": "0700837869",
    "cleaningInfo": "0700837869",
    "mapsUrl": "https://maps.app.goo.gl/eTrnQTm9enFiRiV19"
  },
  {
    "name": "CÔNG TY TNHH CÔNG NGHỆ ASKEY VIỆT NAM",
    "code": "ASKEY-1",
    "shortName": "ASKEY-1",
    "customerCode": "LONG MINH",
    "routeName": "KCN Quế Võ, Bắc Ninh",
    "address": "Lô C7-2,KCN Quế Võ, Phường Nam Sơn, Tỉnh Bắc Ninh, Việt Nam",
    "note": "\"*CÁC NỘI DUNG CẦN CHÚ Ý KHI ĐÓNG TRẢ NHÀ MÁY:\n- Trả  hàng xong chụp luôn BBGH lên nhóm ạ\n- Nghiêm cấm hút thuốc trong địa phận công ty\n- Hàng đóng điện tử yêu cầu vỏ đẹp, sàn chắc khỏe, ko thủng rách, ko dính dầu, nước\nLƯU Ý KHI ĐÓNG XONG HÀNG YÊU CẦU XE VỀ THẲNG CẢNG HẠ, KHÔNG ĐỖ DỪNG NGHỈ DỌC ĐƯỜNG QUÁ 30'. (CHỈ ĐƯỢC PHÉP TRONG 4H DI CHUYỂN TỪ NHÀ MÁY ĐẾN KHI HẠ HÀNG). NẾU PHÁT SINH KHÔNG HẠ KỊP BÁO NGAY LẠI KHI PHÁT SINH. HẠ HÀNG XONG GỬI LUÔN ẢNH PHƠI HẠ HÀNG, ĐỊNH VỊ CHO BÊN E NHÉ. KHÁCH RẤT KHÓ TÍNH VÀ NGHIÊM TRONG VẤN ĐỀ NÀY. NẾU KO THỰC HIỆN ĐÚNG KHÁCH KO THANH TOÁN CƯỚC ĐÂU Ạ.\"",
    "contactName": null,
    "contactPhone": null,
    "warehouseContactInfo": "Xưởng 1",
    "liftInfo": "2301231325",
    "dropInfo": "2301231325",
    "cleaningInfo": "2300540419",
    "mapsUrl": "https://maps.app.goo.gl/YcxGG719wmH7knjR9"
  },
  {
    "name": "CÔNG TY TNHH CÔNG NGHỆ ASKEY VIỆT NAM",
    "code": "ASKEY-2",
    "shortName": "ASKEY-2",
    "customerCode": "LONG MINH",
    "routeName": "KCN Quế Võ, Bắc Ninh",
    "address": "Lô C7-2,KCN Quế Võ, Phường Nam Sơn, Tỉnh Bắc Ninh, Việt Nam",
    "note": "\"*CÁC NỘI DUNG CẦN CHÚ Ý KHI ĐÓNG TRẢ NHÀ MÁY:\n- Trả  hàng xong chụp luôn BBGH lên nhóm ạ\n- Nghiêm cấm hút thuốc trong địa phận công ty\n- Hàng đóng điện tử yêu cầu vỏ đẹp, sàn chắc khỏe, ko thủng rách, ko dính dầu, nước\nLƯU Ý KHI ĐÓNG XONG HÀNG YÊU CẦU XE VỀ THẲNG CẢNG HẠ, KHÔNG ĐỖ DỪNG NGHỈ DỌC ĐƯỜNG QUÁ 30'. (CHỈ ĐƯỢC PHÉP TRONG 4H DI CHUYỂN TỪ NHÀ MÁY ĐẾN KHI HẠ HÀNG). NẾU PHÁT SINH KHÔNG HẠ KỊP BÁO NGAY LẠI KHI PHÁT SINH. HẠ HÀNG XONG GỬI LUÔN ẢNH PHƠI HẠ HÀNG, ĐỊNH VỊ CHO BÊN E NHÉ. KHÁCH RẤT KHÓ TÍNH VÀ NGHIÊM TRONG VẤN ĐỀ NÀY. NẾU KO THỰC HIỆN ĐÚNG KHÁCH KO THANH TOÁN CƯỚC ĐÂU Ạ.\"",
    "contactName": null,
    "contactPhone": null,
    "warehouseContactInfo": "Xưởng 2",
    "liftInfo": "2301231325",
    "dropInfo": "2301231325",
    "cleaningInfo": "2300540419",
    "mapsUrl": "https://maps.app.goo.gl/JXwySTuxyGARCcE57"
  },
  {
    "name": "CÔNG TY TNHH SUNRISE TECHNOLOGY (VIỆT NAM)",
    "code": "SUNRISE",
    "shortName": "SUNRISE",
    "customerCode": "LONG MINH",
    "routeName": "KCN Vân Trung, Nếnh, Bắc Ninh",
    "address": "Một phần Lô CN-09, Khu công nghiệp Vân Trung, Phường Nếnh, Tỉnh Bắc Ninh, Việt Nam",
    "note": "\"3. Nội dung lưu ý kho đóng/trả hàng\n- Lái xe vào nhà máy yêu cầu ăn mặc gọn gàng (quần áo dài )- Nghiêm cấm hút thuốc trong địa phận công ty\n- Hàng đóng điện tử yêu cầu vỏ đẹp, sàn chắc khỏe, không mùi, thủng rách ,dính dầu, nước\"",
    "contactName": null,
    "contactPhone": null,
    "warehouseContactInfo": "0946445198",
    "liftInfo": "2400859689",
    "dropInfo": "2400859689",
    "cleaningInfo": "2400859689",
    "mapsUrl": "https://maps.app.goo.gl/Qh9GMWCAAu2TKXGcA"
  },
  {
    "name": "CÔNG TY TNHH MỘT THÀNH VIÊN SJ TECH VIỆT NAM",
    "code": "SJ TECH",
    "shortName": "SJ",
    "customerCode": "LONG MINH",
    "routeName": "KCN Vân Trung, Nếnh, Bắc Ninh",
    "address": "Lô số CN-16, khu công nghiệp Vân Trung, Phường Nếnh, Tỉnh Bắc Ninh, Việt Nam",
    "note": "\"3. Nội dung lưu ý kho đóng/trả hàng\n- Lái xe vào nhà máy yêu cầu ăn mặc gọn gàng (quần áo dài )\n- Nghiêm cấm hút thuốc trong địa phận công ty\n- Hàng đóng điện tử yêu cầu vỏ đẹp, sàn chắc khỏe, không mùi, thủng rách ,dính dầu, nước\n-----------------------------------------------------------------------------------------------\n(LƯU Ý KHO BẮT BUỘC PHẢI CÓ BIÊN BẢN KÝ XÁC NHẬN ĐÓNG/ TRẢ HÀNG XONG - IN 2 BẢN ĐƯA LÁI XE CẦM THEO KÝ NHẬN\"",
    "contactName": null,
    "contactPhone": null,
    "warehouseContactInfo": "CHUYÊN: 0974987576",
    "liftInfo": "2400763747",
    "dropInfo": "2400763747",
    "cleaningInfo": "2400763747",
    "mapsUrl": "https://maps.app.goo.gl/tRDrmQTXEmMfyEbx9"
  },
  {
    "name": "CÔNG TY TNHH S-CONNECT BG VINA",
    "code": "SCONECT",
    "shortName": "SCONECT",
    "customerCode": "LONG MINH",
    "routeName": "KCN Vân Trung, Nếnh, Bắc Ninh",
    "address": "Lô CN-17, Khu công nghiệp Vân Trung, Phường Nếnh, Tỉnh Bắc Ninh, Việt NaM",
    "note": "\"3. Nội dung lưu ý kho đóng/trả hàng\n- Lái xe vào nhà máy yêu cầu ăn mặc gọn gàng (quần áo dài )\n- Nghiêm cấm hút thuốc trong địa phận công ty\n- Hàng đóng điện tử yêu cầu vỏ đẹp, sàn chắc khỏe, không mùi, thủng rách ,dính dầu, nước\n-----------------------------------------------------------------------------------------------\n(LƯU Ý KHO BẮT BUỘC PHẢI CÓ BIÊN BẢN KÝ XÁC NHẬN ĐÓNG/ TRẢ HÀNG XONG - IN 2 BẢN ĐƯA LÁI XE CẦM THEO KÝ NHẬN\"",
    "contactName": null,
    "contactPhone": null,
    "warehouseContactInfo": "Ms. Huyền – 0358334025\nMs. Ngân -- 0968720506",
    "liftInfo": "2300540419",
    "dropInfo": "2300540419",
    "cleaningInfo": null,
    "mapsUrl": "https://maps.app.goo.gl/7P66XdaioJAfnHb58"
  }
];

export const prodRoutes: ProdRouteSeed[] = [
  {
    "name": "KCN Đồng Văn, Ninh Bình",
    "code": "KCN Đồng Văn",
    "shortName": "KCN ĐỒNG VĂN, HÀ NAM",
    "loadPoint": null,
    "distanceKm": 120,
    "tolls": null,
    "note": null
  },
  {
    "name": "KCN Quế Võ, Nam Sơn, Bắc Ninh",
    "code": "KCN Quế Võ",
    "shortName": "KCN QUẾ VÕ, BẮC NINH",
    "loadPoint": null,
    "distanceKm": 100,
    "tolls": null,
    "note": null
  },
  {
    "name": "KCN Vân Trung, Nếnh, Bắc Ninh",
    "code": "KCN Vân Trung",
    "shortName": "KCN VÂN TRUNG, BẮC GIANG",
    "loadPoint": null,
    "distanceKm": 120,
    "tolls": null,
    "note": null
  }
];

export const prodTractors: ProdTractorSeed[] = [
  {
    "plate": "15E-016.26",
    "driverName": "Nguyễn Duy Tuấn",
    "vehicleClass": "2 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-052.82",
    "driverName": "Đinh Thanh Thịnh",
    "vehicleClass": "2 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-055.79",
    "driverName": "Bùi Văn Hậu",
    "vehicleClass": "2 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-207.01",
    "driverName": "Lê Văn Khải",
    "vehicleClass": "2 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-076.36",
    "driverName": "Hoàng Trọng Hùng",
    "vehicleClass": "2 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-076.50",
    "driverName": "Vũ Văn Trung",
    "vehicleClass": "2 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15C-167.31",
    "driverName": "Lương Văn Long",
    "vehicleClass": "2 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-205.57",
    "driverName": "Nguyễn Văn Hoàn",
    "vehicleClass": "2 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-209.51",
    "driverName": "Phí Xuân Hoàn",
    "vehicleClass": "2 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-209.49",
    "driverName": "Đinh Văn Đại",
    "vehicleClass": "2 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-087.19",
    "driverName": "Trần Trung Hiếu",
    "vehicleClass": "1 CẦU 2 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15E-019.80",
    "driverName": "Nguyễn Huy Vương",
    "vehicleClass": "1 CẦU 2 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-118.47",
    "driverName": "Lục Văn Lô",
    "vehicleClass": "1 CẦU 2 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-118.97",
    "driverName": "Phạm Thanh Sơn",
    "vehicleClass": "1 CẦU 2 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15F-016.98",
    "driverName": "Bùi Văn An",
    "vehicleClass": "1 CẦU 2 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15E-018.83",
    "driverName": "Nguyễn Thế Vũ",
    "vehicleClass": "1 CẦU 2 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15C-184.62",
    "driverName": "Nguyễn Văn Thọ",
    "vehicleClass": "1 CẦU 2 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-039.39",
    "driverName": "Phạm Ngọc Văn",
    "vehicleClass": "1 CẦU 2 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-021.39",
    "driverName": "Dương Văn Thực",
    "vehicleClass": "1 CẦU 2 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-002.14",
    "driverName": "Trần Đức Trung",
    "vehicleClass": "1 CẦU 2 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-085.66",
    "driverName": "Nguyễn Văn Dương",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-116.24",
    "driverName": "Lưu Văn Tuyền",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-117.55",
    "driverName": "Nguyễn Văn Dung",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-119.64",
    "driverName": "Phan Văn Trường",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-149.80",
    "driverName": "Nguyễn Văn Quỳnh",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-119.87",
    "driverName": "Lê Ngọc Long",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-175.17",
    "driverName": "Lê Hải Nam",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-174.81",
    "driverName": "Lê Văn Điệp",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-150.77",
    "driverName": "Lê Quang Tuyền",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-147.38",
    "driverName": "Vũ Văn Chính",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-154.98",
    "driverName": "Tô Viết Thấm",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-154.26",
    "driverName": "Trần Thế Quân",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-154.38",
    "driverName": "Bùi Văn Kiệm",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-176.93",
    "driverName": "Phùng Đắc Phụng",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-174.23",
    "driverName": "Hoàng Quang Thơ",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-176.51",
    "driverName": "Nguyễn Văn Cần",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-104.03",
    "driverName": "Bùi Tiến Dũng",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-121.95",
    "driverName": "Trần Văn Thắng",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  },
  {
    "plate": "15H-061.14",
    "driverName": "Bùi Quang Hường",
    "vehicleClass": "1 CẦU 3 DÀN",
    "brand": null,
    "towCapacityTons": null,
    "fuelLPer100kmLoaded": null,
    "fuelLPer100kmEmpty": null,
    "inspectionDeadline": null,
    "insuranceExpiry": null,
    "preferredRoute": null,
    "note": null
  }
];

export const prodTrailers: ProdTrailerSeed[] = [
  {
    "plate": "15RM-007.55",
    "pairedTractor": "15E-016.26",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15R-182.06",
    "pairedTractor": "15H-052.82",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15R-184.18",
    "pairedTractor": "15H-055.79",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-034.16",
    "pairedTractor": "15H-207.01",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15R-068.52",
    "pairedTractor": "15H-076.36",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15R-089.78",
    "pairedTractor": "15H-076.50",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15R-103.08",
    "pairedTractor": "15C-167.31",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15R-096.89",
    "pairedTractor": "15H-205.57",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-077.01",
    "pairedTractor": "15H-209.51",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-077.00",
    "pairedTractor": "15H-209.49",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-017.97",
    "pairedTractor": "15H-087.19",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-008.02",
    "pairedTractor": "15E-019.80",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-027.54",
    "pairedTractor": "15H-118.47",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-029.34",
    "pairedTractor": "15H-118.97",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-001.41",
    "pairedTractor": "15F-016.98",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-006.78",
    "pairedTractor": "15E-018.83",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-023.26",
    "pairedTractor": "15C-184.62",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-171.96",
    "pairedTractor": "15H-039.39",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-013.12",
    "pairedTractor": "15H-021.39",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-021.85",
    "pairedTractor": "15H-002.14",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-018.38",
    "pairedTractor": "15H-085.66",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-026.14",
    "pairedTractor": "15H-116.24",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-029.44",
    "pairedTractor": "15H-117.55",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-029.71",
    "pairedTractor": "15H-119.64",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-053.76",
    "pairedTractor": "15H-149.80",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-026.28",
    "pairedTractor": "15H-119.87",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-066.61",
    "pairedTractor": "15H-175.17",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-066.67",
    "pairedTractor": "15H-174.81",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-054.53",
    "pairedTractor": "15H-150.77",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-053.05",
    "pairedTractor": "15H-147.38",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-055.47",
    "pairedTractor": "15H-154.98",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-053.12",
    "pairedTractor": "15H-154.26",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-054.29",
    "pairedTractor": "15H-154.38",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-066.65",
    "pairedTractor": "15H-176.93",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-066.60",
    "pairedTractor": "15H-174.23",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-066.62",
    "pairedTractor": "15H-176.51",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-107.28",
    "pairedTractor": "15H-104.03",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-107.29",
    "pairedTractor": "15H-121.95",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  },
  {
    "plate": "15RM-107.33",
    "pairedTractor": "15H-061.14",
    "type": null,
    "maxPayloadTons": null,
    "maxAxleLoadFrontTons": null,
    "maxAxleLoadRearTons": null,
    "inspectionDeadline": null,
    "note": null
  }
];

export const prodPorts: ProdPortSeed[] = [
  {
    "name": "Cảng Tân Vũ",
    "code": "Tân Vũ",
    "classification": "Cảng",
    "legalEntity": "Công ty TNHH Cảng Container Quốc tế Tân Cảng Hải Phòng",
    "address": "ĐT356, KCN Đình Vũ, Đông Hải, Hải Phòng",
    "isLachHuyen": false,
    "opsPortalUrl": "https://eport.haiphongport.com.vn/User/Login",
    "position": null
  },
  {
    "name": "Cảng Đình Vũ",
    "code": "Đình Vũ",
    "classification": "Cảng",
    "legalEntity": "Công ty Cổ Phần Cảng Xanh VIP",
    "address": "Lô KB4 Khu công nghiệp Minh Phương, Phường Đông Hải, Thành phố Hải Phòng, Việt Nam",
    "isLachHuyen": false,
    "opsPortalUrl": "https://eport.dinhvuport.com.vn/",
    "position": null
  },
  {
    "name": "Cảng Nam Đình Vũ",
    "code": "NĐV",
    "classification": "Cảng",
    "legalEntity": "Công ty Cổ phần Đầu tư Dịch vụ và Phát triển Xanh",
    "address": "Khu phi thuế quan và Khu công nghiệp Nam Đình Vũ, Phường Đông Hải 2, Quận Hải An, Hải Phòng.",
    "isLachHuyen": false,
    "opsPortalUrl": "https://smartport.gemadept.com.vn/login",
    "position": null
  },
  {
    "name": "Cảng Nam Hải Đình Vũ",
    "code": "NHĐV",
    "classification": "Cảng",
    "legalEntity": null,
    "address": "Km 6 đường Đình Vũ, Phường Đông Hải, Thành Phố Hải Phòng, Việt Nam",
    "isLachHuyen": false,
    "opsPortalUrl": "https://eport.namhaidvport.com.vn/",
    "position": null
  },
  {
    "name": "Cảng Green Port",
    "code": "Green",
    "classification": "Cảng",
    "legalEntity": null,
    "address": "Số 1 Ngô Quyền, Phường Đông Hải, Thành phố Hải Phòng, Việt Nam",
    "isLachHuyen": false,
    "opsPortalUrl": "https://eport.greenport.com.vn/",
    "position": null
  },
  {
    "name": "Cảng VipGreenPort",
    "code": "VIP",
    "classification": "Cảng",
    "legalEntity": null,
    "address": "Khu kinh tế Đình Vũ – Cát Hải, P. Đông Hải, Tp.Hải Phòng, Việt Nam",
    "isLachHuyen": false,
    "opsPortalUrl": "https://eport.vipgreenport.com.vn/",
    "position": null
  },
  {
    "name": "Cảng Hải An",
    "code": "Hải An",
    "classification": "Cảng",
    "legalEntity": null,
    "address": "Tầng 1, toà nhà Hải An, km 2 đường Đình Vũ, , Thành phố Hải Phòng, Việt Nam",
    "isLachHuyen": false,
    "opsPortalUrl": "https://vietnamhub.vn/login",
    "position": null
  },
  {
    "name": "Cảng Lạch Huyện",
    "code": "HICT",
    "classification": "Cảng",
    "legalEntity": null,
    "address": "Khu Đôn Lương, thị trấn Cát Hải, huyện Cát Hải, thành phố Hải Phòng, Việt Nam",
    "isLachHuyen": true,
    "opsPortalUrl": "https://eport.hict.net.vn/",
    "position": null
  },
  {
    "name": "Cảng TIL",
    "code": "HTIT",
    "classification": "Cảng",
    "legalEntity": null,
    "address": "Bến số 3 & 4 Cảng nước sâu Lạch Huyện, Khu phố Đôn Lương, Đặc khu Cát Hải, Thành Phố Hải Phòng, Việt Nam",
    "isLachHuyen": true,
    "opsPortalUrl": "https://eport.htit.com.vn/",
    "position": null
  },
  {
    "name": "Cảng Chùa Vẽ",
    "code": "CHÙA VẼ",
    "classification": "Cảng",
    "legalEntity": null,
    "address": "Số 5 đường Chùa Vẽ, phường Đông Hải, TP. Hải Phòng. Đây là Chi nhánh Cảng Chùa Vẽ – Cảng Hải Phòng",
    "isLachHuyen": false,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Cảng Mipec",
    "code": "MIPEC",
    "classification": "Cảng",
    "legalEntity": null,
    "address": "Bán đảo Đình Vũ, Khu kinh tế Đình Vũ – Cát Hải, phường Đông Hải, TP Hải Phòng",
    "isLachHuyen": false,
    "opsPortalUrl": "https://eport.mpcport.com/User/Login",
    "position": null
  },
  {
    "name": "Cảng Vimc",
    "code": "VIMC",
    "classification": "Cảng",
    "legalEntity": null,
    "address": "Khu Kinh tế Đình Vũ – Cát Hải, đường ĐT356, phường Đông Hải, TP. Hải Phòng",
    "isLachHuyen": false,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Cảng Hateco",
    "code": "Hateco",
    "classification": "Cảng",
    "legalEntity": null,
    "address": "Bến container số 5&6 Khu cảng Lạch Huyện, Đặc khu Cát Hải, TP. Hải Phòng, Việt Nam",
    "isLachHuyen": true,
    "opsPortalUrl": "https://hhit.com.vn/",
    "position": null
  },
  {
    "name": "Bãi SITC",
    "code": "SITC",
    "classification": "Bãi",
    "legalEntity": null,
    "address": "Cảng Đình Vũ - Đông Hải 2 - Hải An - Hải Phòng",
    "isLachHuyen": false,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Bãi SITC-7",
    "code": "SITC-7",
    "classification": "Bãi",
    "legalEntity": null,
    "address": "Cát Hải, Hải Phòng",
    "isLachHuyen": true,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Bãi ICD Tân Cảng",
    "code": "ICD TÂN CẢNG",
    "classification": "Bãi",
    "legalEntity": null,
    "address": "Lô CN1.1 & CN1.2 KCN Minh Phương, Phường Đông Hải 2, Quận Hải An, Hải Phòng.",
    "isLachHuyen": false,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Bãi GFT",
    "code": "GFT",
    "classification": "Bãi",
    "legalEntity": null,
    "address": "Cát Vũ, KCN Đình Vũ, Đông Hải, Hải Phòng.",
    "isLachHuyen": false,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Bãi Minh Phương",
    "code": "MEDLOG",
    "classification": "Bãi",
    "legalEntity": null,
    "address": "Lô KB1.8 và Lô CN4-4, KCN MP Đình Vũ, phường Đông Hải, TP Hải Phòng",
    "isLachHuyen": false,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Bãi Liên Việt",
    "code": "LIÊN VIỆT",
    "classification": "Bãi",
    "legalEntity": null,
    "address": "KCN Minh Phương, đường Đình Vũ, phường Đông Hải, TP. Hải Phòng",
    "isLachHuyen": false,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Bãi Chân Thật - THT",
    "code": "THT",
    "classification": "Bãi",
    "legalEntity": null,
    "address": "Khu vực KCN Đình Vũ, phường Đông Hải, Hải Phòng.",
    "isLachHuyen": false,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Bãi Nam Hải ICD",
    "code": "NAM HẢI ICD",
    "classification": "Bãi",
    "legalEntity": null,
    "address": "Lô CN3, Khu công nghiệp MP Đình Vũ, phường Đông Hải, TP. Hải Phòng",
    "isLachHuyen": false,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Bãi Vạn Vĩnh Liên",
    "code": "VẠN VĨNH LIÊN",
    "classification": "Bãi",
    "legalEntity": null,
    "address": "KCN Minh Phương – Đường Đình Vũ, phường Đông Hải, TP. Hải Phòng",
    "isLachHuyen": false,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Bãi JJ LOGISTICS",
    "code": "JJLVN",
    "classification": "Bãi",
    "legalEntity": null,
    "address": "ĐƯỜNG NỘI BỘ SỐ 4 KHU CÔNG NGHIỆP MINH\nPHƯƠNG, PHƯỜNG ĐÔNG HẢI, THÀNH PHỐ HẢI PHÒNG (CẠNH NAM HẢI\nICD)",
    "isLachHuyen": false,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Bãi Đình Vũ",
    "code": "ĐÌNH VŨ DEPOT",
    "classification": "Bãi",
    "legalEntity": null,
    "address": "Lô KB4, KCN Minh Phương, đường Đình Vũ, phường Đông Hải, TP. Hải Phòng",
    "isLachHuyen": false,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Bãi MVG 2",
    "code": "MVG 2",
    "classification": "Bãi",
    "legalEntity": null,
    "address": "Khu Dịch vụ cuối tuyến Đình Vũ, phường Đông Hải, Hải Phòng",
    "isLachHuyen": false,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Bãi GIC",
    "code": "GIC",
    "classification": "Bãi",
    "legalEntity": null,
    "address": "Lô CC2, KCN Đình Vũ, phường Đông Hải, TP. Hải Phòng",
    "isLachHuyen": false,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Bãi GLC",
    "code": "GLC",
    "classification": "Bãi",
    "legalEntity": null,
    "address": "Lô đất CN3.2G, KCN Đình Vũ, phường Đông Hải, TP. Hải Phòng",
    "isLachHuyen": false,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Bãi SVL",
    "code": "SVL",
    "classification": "Bãi",
    "legalEntity": null,
    "address": "Khu công nghiệp Nam Đình Vũ, phường Đông Hải, Hải Phòng",
    "isLachHuyen": false,
    "opsPortalUrl": null,
    "position": null
  },
  {
    "name": "Bãi Pan Hải An",
    "code": "PAN",
    "classification": "Bãi",
    "legalEntity": null,
    "address": "Lô KB5, Khu công nghiệp Nam Đình Vũ (Khu 1), Khu kinh tế Đình Vũ – Cát Hải, phường Đông Hải, TP. Hải Phòng",
    "isLachHuyen": false,
    "opsPortalUrl": "https://edepot.panhaian.com/dang-nhap.php",
    "position": null
  }
];

export const prodCarriers: ProdCarrierSeed[] = [
  {
    "name": "CÔNG TY TNHH HÀ AN PHÚ THỌ",
    "shortName": "HÀ AN",
    "taxCode": "2600892725",
    "address": "Số nhà 6, ngõ 2096, đường Hùng Vương, khu 6C, Phường Nông Trang, Thành phố Việt Trì, Tỉnh Phú Thọ, Việt Nam",
    "contactPerson": "TRẦN ANH QUYẾT",
    "phone": "0983418689"
  },
  {
    "name": "CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ TIẾP VẬN ĐỨC THỊNH",
    "shortName": "VC ĐỨC THỊNH",
    "taxCode": "2300975804",
    "address": "Số 21, Phố Nguyễn Đức Ánh, Khu 3, Phường Võ Cường, Tỉnh Bắc Ninh, Việt Nam",
    "contactPerson": "NGUYỄN VĂN THI",
    "phone": "0975184096"
  },
  {
    "name": "CÔNG TY CP SBI",
    "shortName": "SBI",
    "taxCode": "2300575475",
    "address": "Khu đô thị mới Quế Võ II, Phường Phương Liễu, tỉnh Bắc Ninh, Việt Nam",
    "contactPerson": "NGUYỄN DUY HÀ",
    "phone": "0222 3635 362"
  },
  {
    "name": "CÔNG TY TNHH TIẾP VẬN HOÀNG KIM",
    "shortName": "HOÀNG KIM",
    "taxCode": "2300328765",
    "address": "Tòa nhà Trung Thành, Số 10 Nguyễn Đăng Đạo, Phường Kinh Bắc, Tỉnh Bắc Ninh, Việt Nam",
    "contactPerson": "HOÀNG THỊ KIM HOÀ",
    "phone": "0983832868"
  },
  {
    "name": "CÔNG TY CỔ PHẦN TIẾP VẬN KIÊN LONG",
    "shortName": "KIÊN LONG",
    "taxCode": "0201651146",
    "address": "TẦNG 6, SỐ 452 LÊ THÁNH TÔNG, PHƯỜNG NGÔ QUYỀN, THÀNH PHỐ HẢI PHÒNG, VIỆT NAM",
    "contactPerson": "PHÙNG THỊ BÍCH HOÀN",
    "phone": null
  },
  {
    "name": "CÔNG TY TNHH THƯƠNG MẠI J&K LOGISTICS",
    "shortName": "J&K",
    "taxCode": "0201933782",
    "address": "Tầng 3, Lô 16, Khu tái định cư Đằng Hải 1, Phường Hải An, Thành phố Hải Phòng, Việt Nam",
    "contactPerson": "TRẦN THANH ĐOÀN",
    "phone": "0896128279"
  },
  {
    "name": "CÔNG TY CỔ PHẦN THƯƠNG MẠI CHẾ BIẾN THỰC PHẨM VĨNH NIỆM",
    "shortName": "VĨNH NIỆM ( C QUYỀN)",
    "taxCode": "0200669768",
    "address": "Tổ 6 cụm dân cư số 1, Phường Vĩnh Niệm, Quận Lê Chân, Thành phố Hải Phòng, Việt Nam",
    "contactPerson": "VŨ NHÂN QUYỀN",
    "phone": "02253856025"
  },
  {
    "name": "CÔNG TY TNHH THƯƠNG MẠI VÀ DỊCH VỤ VẬN TẢI PCAV",
    "shortName": "PCAV",
    "taxCode": "0202233102",
    "address": "Tổ dân phố 1 Kinh Giao (tại nhà ông Đỗ Văn Thanh), Phường An Dương, Thành phố Hải Phòng, Việt Nam",
    "contactPerson": "LÊ HỒNG PHONG",
    "phone": null
  },
  {
    "name": "CÔNG TY TNHH DỊCH VỤ XNK VÀ VẬN TẢI ĐĂNG QUÂN",
    "shortName": "ĐĂNG QUÂN",
    "taxCode": "0201894910",
    "address": "Số nhà 29A Ngõ 29, Tổ dân phố Hạ Đoạn 3, Phường Đông Hải, Thành phố Hải Phòng, Việt Nam",
    "contactPerson": "NGUYỄN THỊ THU",
    "phone": null
  },
  {
    "name": "CÔNG TY TNHH VẬN TẢI VÀ XUẤT NHẬP KHẨU ĐĂNG QUÂN",
    "shortName": "ĐQ",
    "taxCode": "0202097812",
    "address": "7b1, ngách 7 ngõ 99 phố Tiền Phong, Phường Hải An, Thành phố Hải Phòng, Việt Nam",
    "contactPerson": "ĐẶNG VĂN TÂM",
    "phone": null
  },
  {
    "name": "CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ VẬN TẢI HỒNG TRANG",
    "shortName": "HỒNG TRANG",
    "taxCode": "0201586592",
    "address": "Phòng 230, tầng 2, Khách sạn Dầu khí, số 441 Đà Nẵng, Phường Đông Hải, TP Hải Phòng",
    "contactPerson": "LƯƠNG VĂN THỊNH",
    "phone": "0985775522"
  },
  {
    "name": "CÔNG TY TNHH TIẾP VẬN DUYÊN HẢI",
    "shortName": "DUYÊN HẢI",
    "taxCode": "0201316959",
    "address": "Thửa đất số 592, tổ dân phố số 15, Phường Đằng Hải, Quận Hải An, Thành phố Hải Phòng, Việt Nam",
    "contactPerson": "TRẦN THỊ DUYÊN",
    "phone": null
  },
  {
    "name": "CÔNG TY TNHH CÔNG NGHỆ VẬN TẢI M&M",
    "shortName": "MMTRANS",
    "taxCode": "0202113077",
    "address": "Số 20/33 Tây Trung Hành, Trung Hành 5, Phường Hải An, Thành phố Hải Phòng, Việt Nam",
    "contactPerson": "VŨ THU TRANG",
    "phone": "0798604688"
  },
  {
    "name": "CÔNG TY CỔ PHẦN VÂN LAN",
    "shortName": "VÂN LAN",
    "taxCode": "0200659738",
    "address": "Phòng 311-314 tòa nhà Dầu Khí, số 441 Đà Nẵng, Phường Đông Hải, Thành phố Hải Phòng, Việt Nam",
    "contactPerson": "ĐÀO THANH LAN",
    "phone": null
  },
  {
    "name": "CÔNG TY CỔ PHẦN CUNG ỨNG DỊCH VỤ BIỂN XANH",
    "shortName": "BIỂN XANH",
    "taxCode": "0202207286",
    "address": "THỬA ĐẤT SỐ 244, TỜ BẢN ĐỒ SỐ 46, LÔ 387 KHU TÁI ĐỊNH CƯ 4.3, PHƯỜNG AN BIÊN, THÀNH PHỐ HẢI PHÒNG, VIỆT NAM",
    "contactPerson": "NGUYỄN THỊ BIỂN",
    "phone": "0936905289"
  },
  {
    "name": "CÔNG TY TNHH DỊCH VỤ VẬN TẢI D&S",
    "shortName": "MINH KHÁNH",
    "taxCode": "0202198627",
    "address": "Số 518 đường Lê Thánh Tông, Phường Đông Hải, Thành phố Hải Phòng, Việt Nam",
    "contactPerson": "VŨ THANH SANG",
    "phone": "0902097959"
  },
  {
    "name": "CÔNG TY CỔ PHẦN GIAO NHẬN VẬN TẢI DH-CHI NHÁNH TẠI BẮC NINH",
    "shortName": "DH-BẮC NINH",
    "taxCode": "0102897678-002",
    "address": "Khu Golden Park, Phường Phương Liễu, Tỉnh Bắc Ninh, Việt Nam",
    "contactPerson": "TRỊNH ĐẮC KHOA",
    "phone": null
  }
];
