CREATE VIEW "public"."trips_composite" AS (
  select
    trips.id, trips.trip_code, trips.version, trips.created_by, trips.customer_id,
    trips.customer_reference, trips.truck_id, trips.driver_id, trips.route_id,
    trips.trailer_id, trips.trailer_type, trips.cargo_type_id, trips.container_count,
    trips.status, trips.departure_date, trips.planned_start_at, trips.planned_end_at,
    trips.canonical_origin, trips.canonical_destination, trips.cargo_weight_kg,
    trips.vehicle_capacity_kg, trips.active_trip_pair_id, trips.active_trip_pair_order,
    trips.fuel_mode, trips.fuel_liters_override, trips.fuel_supplement_liters,
    trips.fuel_supplement_reason, trips.tolls_discount, trips.tolls_addition,
    trips.tolls_stations, trips.has_return_cargo, trips.notes, trips.cost_submission_note,
    trips.shipment_id, trips.fulfillment_id, trips.source_shipment_version,
    trips.completed_at, trips.pod_recovered_at, trips.pod_recovered_by,
    trips.paper_order_collected_at, trips.paper_order_collected_by,
    trips.instruction_contact_name, trips.instruction_contact_phone,
    trips.instruction_notes, trips.created_at, trips.updated_at, trips.deleted_at,
    trip_financial_state.driver_salary, trip_financial_state.fuel_price_applied,
    trip_financial_state.fuel_actual_unit_price, trip_financial_state.road_allowance_base_applied,
    trip_financial_state.fuel_loaded_norm_applied, trip_financial_state.fuel_empty_norm_applied,
    trip_financial_state.fuel_fixed_allowance_applied, trip_financial_state.fuel_supplement_norm_applied,
    trip_financial_state.toll_per_station_applied, trip_financial_state.return_cargo_bonus_applied,
    trip_financial_state.fuel_liters, trip_financial_state.total_fuel_cost,
    trip_financial_state.fuel_surcharge_amount, trip_financial_state.fuel_surcharge_snapshot,
    trip_financial_state.fuel_surcharge_snapshot_dirty, trip_financial_state.total_road_allowance,
    trip_financial_state.toll_cost, trip_financial_state.toll_deduction,
    trip_financial_state.road_allowance_override, trip_financial_state.total_cost,
    trip_financial_state.revenue, trip_financial_state.revenue_empty_return,
    trip_financial_state.revenue_combine, trip_financial_state.two_point_delivery_bonus,
    trip_financial_state.vehicle_shift_allowance, trip_financial_state.gross_profit,
    trip_financial_state.revenue_original, trip_financial_state.revenue_overridden_by,
    trip_financial_state.revenue_overridden_at, trip_financial_state.revenue_override_reason,
    trip_financial_state.pricing_source, trip_financial_state.pricing_formula,
    trip_financial_state.pricing_snapshot, trip_financial_state.customer_commission,
    trip_financial_state.trip_wage_days, trip_financial_state.fuel_supplier_id,
    trip_financial_state.vat_rate, trip_financial_state.ar_cost_hash,
    trip_financial_state.ar_snapshot_dirty, trip_financial_state.ar_snapshot_changed_at,
    trip_financial_state.ap_cost_hash, trip_financial_state.ap_snapshot_dirty,
    trip_financial_state.ap_snapshot_changed_at, trip_financial_state.pnl_snapshot_gross_profit,
    trip_carrier_info.carrier_type, trip_carrier_info.external_entity_id,
    trip_carrier_info.external_entity_type, trip_carrier_info.external_freight_cost,
    trip_carrier_info.external_plate_number, trip_carrier_info.external_carrier_vehicle_id,
    trip_carrier_info.external_driver_name, trip_carrier_info.external_driver_phone
  from trips
  left join trip_financial_state on trip_financial_state.trip_id = trips.id
  left join trip_carrier_info on trip_carrier_info.trip_id = trips.id
);