-- O2C reconciliation: drop LOCKED, single terminal state.
-- docs/prd/O2C dev.md (01/08/2026). plan: 260801-2200-o2c-drop-locked-reconciliation.
--
-- This migration is forward-only (dev/staging DB is resettable). It:
--   1. Drops LOCKED from trip_status via the safe 4-step PG enum rewrite
--      (CREATE new → ALTER COLUMN USING CASE → DROP old → RENAME). PG
--      `ALTER TYPE ... DROP VALUE` leaves a tombstone that blocks later
--      column reorders, so the swap pattern is required.
--   2. Adds the carrier_type CHECK constraint (column was varchar(20) with
--      no constraint — P&L split could silently mis-bucket).
--   3. Migrates external_carrier_id (locked FK → customers.id) to two plain
--      nullable soft columns: external_entity_id + external_entity_type
--      (no DB FK — app-layer resolveExternalCarrier helper).
--   4. Drops TRIP_LOCKED / TRIP_UNLOCKED from notification_type (same swap
--      pattern — these drove the old LOCK transition).
--   5. Adds the O2C columns: pod_recovered_at/by (POD gate), ar snapshot
--      dirty-flag columns, field-ops hand-off timestamps.
--
-- Pre-migration audit (run before deploying, paste results here):
--   \d+ trips                       -- confirm only trips.status is trip_status
--   SELECT obj dependents:
--     SELECT DISTINCT dep.objid::regclass
--     FROM pg_depend d
--     JOIN pg_type t ON t.oid = d.refobjid
--     WHERE t.typname = 'trip_status' AND d.deptype = 'n';
--   -- Indexes/views/materialized views referencing 'LOCKED' must be DROP/CREATED
--   -- around the type swap. Verified at HEAD: no partial index WHERE status =
--   'LOCKED'; trips_status_idx is non-partial and rebuilds implicitly.

-- ─── 1. trip_status: drop LOCKED (fold LOCKED rows → COMPLETED) ───────────────
CREATE TYPE trip_status_new AS ENUM
  ('CREATED', 'IN_TRANSIT', 'COMPLETED', 'CANCELED');

-- The column has a DEFAULT 'CREATED' that blocks the implicit cast. Drop it.
-- Two partial unique indexes reference the old trip_status type explicitly
-- (trips_fulfillment_id_live_uniq, trips_shipment_without_fulfillment_live_uniq
-- — both have `WHERE status <> 'CANCELED'::trip_status`); DROP them before the
-- type swap and recreate afterwards.
-- Fold LOCKED rows → COMPLETED while the column is still the old type (both are
-- valid old-enum values), so the subsequent ALTER TYPE cast to the new
-- (LOCKED-free) enum never encounters a value it can't represent.
ALTER TABLE trips ALTER COLUMN status DROP DEFAULT;
DROP INDEX IF EXISTS trips_fulfillment_id_live_uniq;
DROP INDEX IF EXISTS trips_shipment_without_fulfillment_live_uniq;
UPDATE trips SET status = 'COMPLETED' WHERE status::text = 'LOCKED';

ALTER TABLE trips
  ALTER COLUMN status TYPE trip_status_new
  USING (status::text)::trip_status_new;

DROP TYPE trip_status;
ALTER TYPE trip_status_new RENAME TO trip_status;

ALTER TABLE trips ALTER COLUMN status SET DEFAULT 'CREATED';

-- Recreate the partial unique indexes against the renamed type.
CREATE UNIQUE INDEX trips_fulfillment_id_live_uniq
  ON trips (fulfillment_id)
  WHERE fulfillment_id IS NOT NULL AND status <> 'CANCELED'::trip_status;
CREATE UNIQUE INDEX trips_shipment_without_fulfillment_live_uniq
  ON trips (shipment_id)
  WHERE shipment_id IS NOT NULL AND fulfillment_id IS NULL AND status <> 'CANCELED'::trip_status;

-- ─── 2. carrier_type CHECK constraint + data cleanup ──────────────────────────
UPDATE trips SET carrier_type = 'OWN'
  WHERE carrier_type IS NULL OR carrier_type NOT IN ('OWN', 'EXTERNAL');

ALTER TABLE trips ADD CONSTRAINT trips_carrier_type_check
  CHECK (carrier_type IN ('OWN', 'EXTERNAL'));

-- ─── 3. external_carrier_id → soft columns (external_entity_id/type) ─────────
-- Backfill EXTERNAL rows as CUSTOMER-typed (the old FK targeted customers.id),
-- then drop external_carrier_id and its FK. The FK name is auto-generated by
-- Postgres; drop by lookup so this is idempotent regardless of the name.
ALTER TABLE trips ADD COLUMN IF NOT EXISTS external_entity_id integer;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS external_entity_type varchar(20);

UPDATE trips
  SET external_entity_id = external_carrier_id,
      external_entity_type = 'CUSTOMER'
  WHERE external_carrier_id IS NOT NULL;

DO $$
DECLARE
  fk_name text;
BEGIN
  SELECT conname INTO fk_name
  FROM pg_constraint
  WHERE conrelid = 'trips'::regclass
    AND contype = 'f'
    AND conkey[1] = (
      SELECT attnum FROM pg_attribute
      WHERE attrelid = 'trips'::regclass AND attname = 'external_carrier_id'
    )
  LIMIT 1;
  IF fk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE trips DROP CONSTRAINT %I', fk_name);
  END IF;
END $$;

ALTER TABLE trips DROP COLUMN IF EXISTS external_carrier_id;

-- ─── 4. notification_type: drop TRIP_LOCKED / TRIP_UNLOCKED ──────────────────
-- The e-POD acceptance path now emits TRIP_COMPLETED (already a member). The
-- old TRIP_LOCKED / TRIP_UNLOCKED values drove the dropped LOCK transition.
-- Fold any existing TRIP_LOCKED rows → TRIP_COMPLETED; remove TRIP_UNLOCKED
-- rows (they reversed a transition that no longer exists).
CREATE TYPE notification_type_new AS ENUM (
  'TRIP_CREATED', 'TRIP_DISPATCHED', 'TRIP_IN_TRANSIT', 'TRIP_COMPLETED',
  'TRIP_CANCELED', 'PAYMENT_RECEIVED', 'PENALTY_CREATED',
  'PENALTY_CANCELED', 'OVERDUE_PAYMENT', 'SALARY_PERIOD_CLOSING',
  'SYSTEM_ANNOUNCEMENT', 'ADVANCE_SETTLEMENT_APPROVED', 'SHIPMENT_HANDOFF'
);

DELETE FROM notifications WHERE type IN ('TRIP_LOCKED', 'TRIP_UNLOCKED');

ALTER TABLE notifications
  ALTER COLUMN type TYPE notification_type_new
  USING type::text::notification_type_new;

DROP TYPE notification_type;
ALTER TYPE notification_type_new RENAME TO notification_type;

-- ─── 5. O2C new columns on trips ──────────────────────────────────────────────
-- POD-recovery gate (physical paper return — distinct from digital e-POD).
ALTER TABLE trips ADD COLUMN IF NOT EXISTS pod_recovered_at timestamptz;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS pod_recovered_by integer;

-- AR snapshot dirty-flag (costs stay editable after COMPLETED; snapshot tracks drift).
ALTER TABLE trips ADD COLUMN IF NOT EXISTS ar_cost_hash varchar(64);
ALTER TABLE trips ADD COLUMN IF NOT EXISTS ar_snapshot_dirty boolean NOT NULL DEFAULT false;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS ar_snapshot_changed_at timestamptz;

-- Field-ops hand-off timestamps (Ops paper-order collected + Driver order-accepted).
ALTER TABLE trips ADD COLUMN IF NOT EXISTS paper_order_collected_at timestamptz;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS driver_order_accepted_at timestamptz;

-- ─── 6. trip_expenses.approved_at / approved_by ──────────────────────────────
-- Real approval timestamp (NULL until an accountant approves). The delete-
-- authorization matrix keys off this, not approvalStatus (which defaults to
-- 'APPROVED' for legacy rows and would make everything undeletable).
ALTER TABLE trip_expenses ADD COLUMN IF NOT EXISTS approved_at timestamptz;
ALTER TABLE trip_expenses ADD COLUMN IF NOT EXISTS approved_by integer;

-- delete_requests queue table (O2C session-scoped delete rules).
CREATE TABLE IF NOT EXISTS delete_requests (
  id serial PRIMARY KEY,
  entity_type varchar(50) NOT NULL,
  entity_id integer NOT NULL,
  requested_by integer NOT NULL,
  reason text,
  status varchar(20) NOT NULL DEFAULT 'PENDING',
  reviewed_by integer,
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS delete_requests_status_idx ON delete_requests (status);
