import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { eq } from 'drizzle-orm';
import { Role } from '@tingting/shared';
import { db, client } from '../db';
import * as s from '../db/schema';
import { getPhoiPhieuTienDuong } from '../services/phoi-phieu-control.service';
import { confirmAccountingExpenses } from '../services/expense-accounting-write.service';
import { ApiError } from '../errors';
const cleanup: Array<() => Promise<unknown>> = [];
const key = `driver-confirm-${Date.now()}-${Math.random().toString(36).slice(2)}`;
test('corrected driver DTO carries current version; stale confirmation has no effect', async () => {
  const [u] = await db.insert(s.users).values({ username: key, passwordHash: 'x', role: Role.ACCOUNTANT }).returning(); cleanup.unshift(() => db.delete(s.users).where(eq(s.users.id, u.id)));
  const [d] = await db.insert(s.drivers).values({ name: key, userId: u.id }).returning(); cleanup.unshift(() => db.delete(s.drivers).where(eq(s.drivers.id, d.id)));
  const [customer] = await db.insert(s.customers).values({ name: key }).returning(); cleanup.unshift(() => db.delete(s.customers).where(eq(s.customers.id, customer.id)));
  const [route] = await db.insert(s.routes).values({ name: key }).returning(); cleanup.unshift(() => db.delete(s.routes).where(eq(s.routes.id, route.id)));
  const [shipment] = await db.insert(s.shipments).values({ customerId: customer.id, cargoMode: 'FCL', status: 'DISPATCHED' }).returning(); cleanup.unshift(() => db.delete(s.shipments).where(eq(s.shipments.id, shipment.id)));
  const [trip] = await db.insert(s.trips).values({ tripCode: key.slice(0, 50), driverId: d.id, customerId: customer.id, routeId: route.id, shipmentId: shipment.id, status: 'COMPLETED', completedAt: new Date('2026-09-22T08:00:00Z'), departureDate: '2026-09-22' }).returning(); cleanup.unshift(() => db.delete(s.trips).where(eq(s.trips.id, trip.id)));
  const [cost] = await db.insert(s.driverIncidentalCosts).values({ tripId: trip.id, driverId: d.id, costType: 'OTHER', costGroup: 'DRIVER_ROAD', payerKind: 'USER', feeName: 'Phụ cấp cấu hình', amount: '110000', driverEnteredAmount: '150000', customerChargeAmount: '0', occurredAt: '2026-09-22' }).returning(); cleanup.unshift(() => db.delete(s.driverIncidentalCosts).where(eq(s.driverIncidentalCosts.id, cost.id)));
  let dto = await getPhoiPhieuTienDuong(trip.id); assert.equal(dto.rows[0].version, 1, 'Unlinked legacy source will start at version1');
  const [source] = await db.insert(s.expenseAccountingSources).values({ sourceKind: 'DRIVER', sourceId: cost.id, shipmentId: shipment.id, tripId: trip.id, recordedById: u.id, version: 4 }).returning(); cleanup.unshift(() => db.delete(s.expenseAccountingSources).where(eq(s.expenseAccountingSources.id, source.id)));
  dto = await getPhoiPhieuTienDuong(trip.id); assert.equal(dto.rows[0].version, 4); assert.equal(dto.rows[0].amount, 110000); assert.equal(dto.rows[0].driverEnteredAmount, 150000);
  const actor = { userId: u.id, role: Role.ACCOUNTANT };
  await assert.rejects(() => db.transaction(tx => confirmAccountingExpenses(tx, actor, [{ sourceKind: 'DRIVER', sourceId: cost.id, expectedVersion: 1 }])), (error: unknown) => error instanceof ApiError && error.statusCode === 409);
  const [unchanged] = await db.select().from(s.expenseAccountingSources).where(eq(s.expenseAccountingSources.id, source.id)); assert.equal(unchanged.version, 4); assert.equal(unchanged.confirmedAt, null); assert.equal(unchanged.linkedTripExpenseId, null);
  const rollback = new Error('ROLLBACK_TEST_CONFIRMATION');
  await assert.rejects(() => db.transaction(async tx => { const confirmed = await confirmAccountingExpenses(tx, actor, [{ sourceKind: 'DRIVER', sourceId: cost.id, expectedVersion: dto.rows[0].version }]); assert.equal(confirmed[0].version, 5); assert(confirmed[0].confirmedAt); assert.equal(confirmed[0].amount, '110000'); throw rollback; }), error => error === rollback);
});
after(async () => { try { for (const remove of cleanup) await remove(); } finally { await client.end(); } });
