import { z } from 'zod';

export const GOVERNANCE_SUBJECT_TYPES = [
  'TRIP',
  'SHIPMENT',
  'PAYMENT_RECEIPT',
  'PAYMENT_REFUND',
  'VENDOR_PAYMENT',
  'CARRIER_PAYMENT',
  'DRIVER_PAYOUT',
  'COMMISSION',
  'PENALTY',
  'DEBT_OFFSET',
  'ADVANCE_REQUEST',
  'ADVANCE_SETTLEMENT',
  'TRIP_EXPENSE',
  'FUEL_INVOICE',
  'CREDIT_OVERRIDE',
  'COMPANY_EXPENSE',
  'BILLING_DOCUMENT',
  'SALARY_CONFIRMATION',
  'SALARY_PERIOD',
  'PROFIT_DISTRIBUTION',
  'PRICE_CONFIG',
  'ANCILLARY_REVENUE',
  'EXCEPTION',
  'TREASURY_ACCOUNT',
  'TREASURY_MOVEMENT',
] as const;

export const GOVERNANCE_ACTION_KINDS = [
  'TRIP_AR_ADJUSTMENT',
  'TRIP_REOPEN',
  'SHIPMENT_COST_CONFIRMATION',
  'SHIPMENT_REOPEN_REQUEST',
  'TRIP_EXPENSE_APPROVAL',
  'FUEL_INVOICE_CORRECTION',
  'FUEL_INVOICE_APPROVAL',
  'CREDIT_OVERRIDE_APPROVAL',
  'DEBT_OFFSET_APPROVAL',
  'DEBT_OFFSET_CANCEL',
  'ADVANCE_REQUEST_APPROVAL',
  'ADVANCE_REQUEST_REJECTION',
  'ADVANCE_SETTLEMENT_CORRECTION',
  'ADVANCE_SETTLEMENT_REVERSAL',
  'PAYMENT_RECEIPT',
  'PAYMENT_REFUND',
  'VENDOR_PAYMENT',
  'CARRIER_PAYMENT',
  'DRIVER_PAYOUT',
  'COMMISSION',
  'PENALTY_CREATE',
  'PENALTY_CANCEL',
  'COMPANY_EXPENSE',
  'PROFIT_DISTRIBUTION',
  'TRIP_FINANCIAL_CHANGE',
  'TRIP_FINANCIAL_CLOSE',
  'DEBIT_NOTE_ISSUE',
  'DEBIT_NOTE_ADJUSTMENT',
  'SALARY_CONFIRMATION',
  'SALARY_REOPEN',
  'SALARY_PERIOD_CLOSE',
  'SALARY_PERIOD_REOPEN',
  'SALARY_PERIOD_ADJUSTMENT',
  'PRICE_CONFIG_CHANGE',
  'ANCILLARY_REVENUE_CHANGE',
  'FINANCIAL_EXCEPTION',
  'TREASURY_ACCOUNT_SETUP',
  'TREASURY_CUTOVER',
  'TREASURY_MOVEMENT_REVERSAL',
  'SHIPMENT_DELETE_REQUEST',
  'CONTAINER_EDIT_REQUEST',
] as const;

export const GOVERNANCE_ACTION_STATUSES = [
  'PENDING_CHECK',
  'PENDING_APPROVAL',
  'APPROVED',
  'REJECTED',
  'RETURNED_FOR_EVIDENCE',
  'CANCELED',
  'SUPERSEDED',
] as const;

export const GOVERNANCE_CAPABILITIES = [
  'GOVERNANCE_CREATE',
  'FINANCE_CHECK',
  'FINANCE_APPROVE_STANDARD',
  'FINANCE_APPROVE_DIRECTOR',
  'PRICE_APPROVE',
  'PERIOD_CLOSE_APPROVE',
  'RECOVERABLE_COST_REQUEST',
  'TRIP_CLOSE_REQUEST',
  'TREASURY_OPERATE',
  'TREASURY_ADMIN',
] as const;

export const GOVERNANCE_ALLOWED_ACTIONS = [
  'CHECK',
  'APPROVE',
  'REJECT',
  'RETURN_FOR_EVIDENCE',
  'CANCEL',
] as const;

export type GovernanceSubjectType = typeof GOVERNANCE_SUBJECT_TYPES[number];
export type GovernanceActionKind = typeof GOVERNANCE_ACTION_KINDS[number];
export type GovernanceActionStatus = typeof GOVERNANCE_ACTION_STATUSES[number];
export type GovernanceCapability = typeof GOVERNANCE_CAPABILITIES[number];
export type GovernanceAllowedAction = typeof GOVERNANCE_ALLOWED_ACTIONS[number];

// 2026-09-11 (maker-checker removal): the staged-decision request shapes are
// gone with the governance_actions queue. Only the in-request decision body
// (expectedVersion + reason) survives — live endpoints still validate it.
export const governanceActionDecisionSchema = z.object({
  expectedVersion: z.coerce.number().int().positive(),
  reason: z.string().trim().min(1, 'Lý do là bắt buộc').max(1000),
});

export type GovernanceActionDecisionInput = z.infer<typeof governanceActionDecisionSchema>;
