import { Role } from '../constants';
import type { Tour } from './schema';

const TOUR_CATALOG_DATA = {
  'manager-dashboard-overview': { id: 'manager-dashboard-overview', version: 1, title: 'Tổng quan vận hành', summary: 'Đọc nhanh KPI và việc cần xử lý trong ngày.', description: 'Hướng dẫn tổng quan vận hành cho quản lý.', category: 'operations', estimatedMinutes: 3, aliases: ['tổng quan vận hành', 'dashboard'], roles: [Role.MANAGER, Role.ADMIN], steps: [{ title: 'Mở tổng quan', body: 'Trang này tóm tắt các chỉ số vận hành hiện tại.', directive: { kind: 'navigate', routeKey: 'dashboard', highlight: { targetId: 'dashboard-kpis', durationMs: 3000 } } }, { title: 'Đọc việc cần xử lý', body: 'Kiểm tra các cảnh báo trước khi điều phối chuyến.', directive: { kind: 'scrollTo', targetId: 'dashboard-attention', durationMs: 3000 } }] },
  'create-trip': { id: 'create-trip', version: 3, title: 'Tạo chuyến vận chuyển', summary: 'Chọn khách, tuyến và lưu một lệnh vận chuyển.', description: 'Hướng dẫn tạo lệnh vận chuyển mới.', category: 'operations', estimatedMinutes: 4, prerequisites: ['Khách hàng và tuyến đường đã được khai báo.'], aliases: ['tạo chuyến', 'tạo lệnh', 'lệnh vận chuyển'], roles: [Role.MANAGER, Role.ADMIN], steps: [{ title: 'Mở form tạo chuyến', body: 'Bắt đầu một lệnh vận chuyển mới.', directive: { kind: 'navigate', routeKey: 'tripNew' } }, { title: 'Chọn khách hàng', body: 'Chọn đơn vị thuê chuyến.', directive: { kind: 'scrollTo', targetId: 'customerId', durationMs: 3000 } }, { title: 'Chọn tuyến', body: 'Chọn tuyến đường và loại hàng phù hợp.', directive: { kind: 'scrollTo', targetId: 'routeId', durationMs: 3000 } }, { title: 'Lưu chuyến', body: 'Kiểm tra lại rồi bấm Tạo chuyến.', directive: { kind: 'scrollTo', targetId: 'trip-new-submit', durationMs: 3000 }, completionEvent: 'trip.created' }] },
  'dispatch-trip': { id: 'dispatch-trip', version: 1, title: 'Cho chuyến khởi hành', summary: 'Điều xe và chuyển chuyến sẵn sàng sang khởi hành.', description: 'Hướng dẫn điều vận một chuyến thực tế.', category: 'operations', estimatedMinutes: 3, prerequisites: ['Cần có chuyến ở trạng thái sẵn sàng điều vận.'], aliases: ['điều vận', 'khởi hành', 'phân xe'], roles: [Role.MANAGER, Role.ADMIN], steps: [{ title: 'Mở điều vận', body: 'Chọn một chuyến thực tế đang chờ điều vận.', directive: { kind: 'navigate', routeKey: 'dispatch', highlight: { targetId: 'dispatch-ready-list', durationMs: 3000 } } }, { title: 'Cho chuyến khởi hành', body: 'Thực hiện thao tác điều vận theo quy trình hiện có.', directive: { kind: 'scrollTo', targetId: 'dispatch-primary-action', durationMs: 3000 }, completionEvent: 'trip.dispatched' }] },
  'lock-trip': { id: 'lock-trip', version: 1, title: 'Khóa chuyến hoàn thành', summary: 'Kiểm tra số liệu và khóa một chuyến đã hoàn thành.', description: 'Hướng dẫn khóa sổ chuyến hoàn thành.', category: 'operations', estimatedMinutes: 3, prerequisites: ['Cần có chuyến COMPLETED với số liệu đã kiểm tra.'], aliases: ['khóa chuyến', 'chốt chuyến', 'khóa sổ'], roles: [Role.MANAGER, Role.ADMIN], steps: [{ title: 'Mở danh sách chuyến', body: 'Tìm một chuyến đã hoàn thành.', directive: { kind: 'navigate', routeKey: 'trips' } }, { title: 'Kiểm tra số liệu', body: 'Mở chi tiết chuyến và kiểm tra phần tài chính.', directive: { kind: 'scrollTo', targetId: 'trip-detail-financials', durationMs: 3000 } }, { title: 'Khóa chuyến', body: 'Chỉ khóa khi số liệu đã đúng vì chuyến sẽ không còn chỉnh sửa được.', directive: { kind: 'scrollTo', targetId: 'trip-detail-lock', durationMs: 3000 }, completionEvent: 'trip.locked' }] },
  'review-pnl': { id: 'review-pnl', version: 1, title: 'Đọc báo cáo lãi lỗ', summary: 'Chọn kỳ và đối chiếu các chỉ số P&L.', description: 'Hướng dẫn xem báo cáo lãi lỗ theo kỳ.', category: 'finance', estimatedMinutes: 3, aliases: ['lãi lỗ', 'p&l', 'báo cáo tài chính'], roles: [Role.MANAGER, Role.ACCOUNTANT, Role.ADMIN], steps: [{ title: 'Mở báo cáo', body: 'Chọn kỳ cần đối chiếu.', directive: { kind: 'navigate', routeKey: 'finance', highlight: { targetId: 'finance-period', durationMs: 3000 } } }, { title: 'Đọc chỉ số chính', body: 'Xem doanh thu, chi phí và lợi nhuận trước khi đi sâu theo xe.', directive: { kind: 'scrollTo', targetId: 'finance-kpis', durationMs: 3000 } }] },
  'accounting-overview': { id: 'accounting-overview', version: 1, title: 'Tổng quan kế toán', summary: 'Xem công nợ và các khoản cần xử lý.', description: 'Hướng dẫn điểm bắt đầu cho kế toán.', category: 'finance', estimatedMinutes: 2, aliases: ['tổng quan kế toán', 'công nợ'], roles: [Role.ACCOUNTANT, Role.ADMIN], steps: [{ title: 'Mở công nợ phải thu', body: 'Đây là nơi theo dõi số tiền khách hàng còn phải thanh toán.', directive: { kind: 'navigate', routeKey: 'debt', highlight: { targetId: 'debt-aging', durationMs: 3000 } } }, { title: 'Chọn khách cần xử lý', body: 'Dùng danh sách công nợ để mở chi tiết khách hàng.', directive: { kind: 'scrollTo', targetId: 'debt-customer-list', durationMs: 3000 } }] },
  'update-trip-figures': { id: 'update-trip-figures', version: 1, title: 'Hoàn thiện số liệu chuyến', summary: 'Cập nhật số liệu tài chính thực tế của một chuyến.', description: 'Hướng dẫn cập nhật số liệu tài chính chuyến.', category: 'finance', estimatedMinutes: 3, prerequisites: ['Chọn một chuyến mà bạn có quyền sửa.'], aliases: ['số liệu chuyến', 'cập nhật chi phí'], roles: [Role.ACCOUNTANT, Role.ADMIN], steps: [{ title: 'Mở danh sách chuyến', body: 'Chọn chuyến cần hoàn thiện số liệu.', directive: { kind: 'navigate', routeKey: 'trips' } }, { title: 'Lưu số liệu tài chính', body: 'Cập nhật số liệu thực tế rồi lưu phần tài chính.', directive: { kind: 'scrollTo', targetId: 'trip-edit-financial-submit', durationMs: 3000 }, completionEvent: 'trip.figures_saved' }] },
  'record-receivable-payment': { id: 'record-receivable-payment', version: 1, title: 'Ghi nhận thanh toán khách hàng', summary: 'Ghi nhận một khoản thu vào công nợ phải thu.', description: 'Hướng dẫn ghi nhận thanh toán khách hàng.', category: 'finance', estimatedMinutes: 3, prerequisites: ['Cần có khách hàng còn công nợ.'], aliases: ['ghi nhận thanh toán', 'thu tiền', 'công nợ'], roles: [Role.MANAGER, Role.ACCOUNTANT, Role.ADMIN], steps: [{ title: 'Mở công nợ', body: 'Chọn khách hàng cần ghi nhận thanh toán.', directive: { kind: 'navigate', routeKey: 'debt', highlight: { targetId: 'debt-customer-list', durationMs: 3000 } } }, { title: 'Mở form thanh toán', body: 'Mở chi tiết khách hàng rồi chọn ghi nhận thanh toán.', directive: { kind: 'scrollTo', targetId: 'debt-record-payment', durationMs: 3000 } }, { title: 'Lưu thanh toán', body: 'Nhập số tiền thực tế và lưu.', directive: { kind: 'scrollTo', targetId: 'debt-payment-submit', durationMs: 3000 }, completionEvent: 'receivable.payment_recorded' }] },
  'fuel-config': { id: 'fuel-config', version: 2, title: 'Nhập định mức nhiên liệu', summary: 'Cập nhật định mức dầu và đơn giá hiện hành.', description: 'Hướng dẫn cấu hình định mức nhiên liệu.', category: 'configuration', estimatedMinutes: 4, aliases: ['định mức dầu', 'nhiên liệu', 'dầu'], roles: [Role.MANAGER, Role.ACCOUNTANT, Role.ADMIN], steps: [{ title: 'Mở định mức nhiên liệu', body: 'Mở trang cấu hình nhiên liệu.', directive: { kind: 'navigate', routeKey: 'configFuel', highlight: { targetId: 'fuel-loaded-norm-field', durationMs: 3000 } } }, { title: 'Kiểm tra định mức xe không', body: 'Đối chiếu định mức cho xe chạy không hàng.', directive: { kind: 'scrollTo', targetId: 'fuel-empty-norm-field', durationMs: 3000 } }, { title: 'Kiểm tra mức bổ sung', body: 'Cập nhật mức bổ sung khi quy trình nội bộ yêu cầu.', directive: { kind: 'scrollTo', targetId: 'fuel-supplement-field', durationMs: 3000 } }, { title: 'Cập nhật đơn giá dầu', body: 'Đối chiếu đơn giá áp dụng trước khi lưu.', directive: { kind: 'scrollTo', targetId: 'fuel-unit-price-field', durationMs: 3000 } }, { title: 'Lưu cấu hình', body: 'Lưu sau khi đối chiếu đơn giá dầu.', directive: { kind: 'scrollTo', targetId: 'fuel-save-config-button', durationMs: 3000 }, completionEvent: 'config.fuel_saved' }] },
  'system-readiness': { id: 'system-readiness', version: 1, title: 'Kiểm tra dữ liệu nền', summary: 'Kiểm tra các danh mục cần thiết trước khi vận hành.', description: 'Hướng dẫn kiểm tra cấu hình hệ thống.', category: 'administration', estimatedMinutes: 3, aliases: ['dữ liệu nền', 'sẵn sàng hệ thống'], roles: [Role.ADMIN], steps: [{ title: 'Mở cấu hình', body: 'Kiểm tra các danh mục nền mà hệ thống sử dụng.', directive: { kind: 'navigate', routeKey: 'config', highlight: { targetId: 'config-grid', durationMs: 3000 } } }, { title: 'Kiểm tra danh mục', body: 'Mở từng danh mục còn thiếu để bổ sung bằng dữ liệu thật.', directive: { kind: 'scrollTo', targetId: 'config-grid', durationMs: 3000 } }] },
  'manage-users': { id: 'manage-users', version: 1, title: 'Kiểm tra tài khoản và phân quyền', summary: 'Rà soát danh sách tài khoản và vai trò.', description: 'Hướng dẫn quản lý người dùng.', category: 'administration', estimatedMinutes: 3, aliases: ['người dùng', 'phân quyền', 'tài khoản'], roles: [Role.ADMIN], steps: [{ title: 'Mở người dùng', body: 'Dùng bộ lọc vai trò để rà soát tài khoản.', directive: { kind: 'navigate', routeKey: 'users', highlight: { targetId: 'users-role-filters', durationMs: 3000 } } }, { title: 'Kiểm tra danh sách', body: 'Xem bảng tài khoản hoặc mở form thêm tài khoản khi cần.', directive: { kind: 'scrollTo', targetId: 'users-table', durationMs: 3000 } }] },
  'review-audit-log': { id: 'review-audit-log', version: 1, title: 'Kiểm tra nhật ký người dùng', summary: 'Dùng bộ lọc để rà soát các thao tác gần đây.', description: 'Hướng dẫn xem nhật ký thao tác.', category: 'administration', estimatedMinutes: 2, aliases: ['nhật ký', 'audit log'], roles: [Role.MANAGER, Role.ADMIN], steps: [{ title: 'Mở nhật ký', body: 'Dùng bộ lọc để giới hạn khoảng thời gian hoặc người dùng.', directive: { kind: 'navigate', routeKey: 'auditLogs', highlight: { targetId: 'audit-filters', durationMs: 3000 } } }, { title: 'Đọc kết quả', body: 'Kiểm tra bảng nhật ký trước khi điều tra một thao tác cụ thể.', directive: { kind: 'scrollTo', targetId: 'audit-table', durationMs: 3000 } }] },
} satisfies Record<string, Tour>;

export const TOUR_CATALOG = TOUR_CATALOG_DATA;
export type TourId = keyof typeof TOUR_CATALOG;
export const TOUR_IDS = Object.keys(TOUR_CATALOG) as TourId[];

export function toursForRole(role: Role): readonly Tour[] {
  return TOUR_IDS.map((id) => TOUR_CATALOG[id]).filter((tour) => (tour.roles as readonly Role[]).includes(role));
}

export function getTour(id: string): Tour | undefined {
  return TOUR_CATALOG[id as TourId];
}
