import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { beforeEach, expect, it, vi } from 'vitest';
import type { ReactNode } from 'react';
import type { ExpenseWorkRow } from '@tingting/shared';
const create = vi.hoisted(() => vi.fn());
vi.mock('../../api/expenseAccountingClient', () => ({ expenseAccountingClient: { create } }));
vi.mock('../../components/UI', () => ({ Drawer: ({ children, footer }: { children: ReactNode; footer: ReactNode }) => <section>{children}{footer}</section> }));
import { ExpenseCreateDrawer } from './ExpenseCreateDrawer';
const work = { tripId: 10, shipmentCode: 'BL7', containerNumber: 'CONT7' } as ExpenseWorkRow;
const catalog = { staff: [], accounts: [], accountants: [], opsUsers: [], advances: [], suppliers: [], expenseTypes: [] };
beforeEach(() => { create.mockReset().mockResolvedValue({}); });
it('sends explicit toll treatment independently of the edited fee name and preserves a failed draft/key', async () => {
  create.mockRejectedValueOnce(new Error('Mất phản hồi')).mockResolvedValueOnce({});
  const onClose = vi.fn();
  render(<QueryClientProvider client={new QueryClient({ defaultOptions: { mutations: { retry: false } } })}><ExpenseCreateDrawer work={work} catalog={catalog} initialGroup="DRIVER_ROAD" onClose={onClose} /></QueryClientProvider>);
  fireEvent.click(screen.getByRole('combobox', { name: /Loại chi phí lái xe/ }));
  fireEvent.click(await screen.findByRole('option', { name: 'Vé cầu đường' }));
  fireEvent.change(screen.getByLabelText(/Thực chi/), { target: { value: '80000' } });
  fireEvent.change(screen.getByLabelText(/Tên khoản chi/), { target: { value: 'Vé qua trạm' } });
  expect(screen.getByLabelText(/Thực thu/)).toBeDisabled();
  fireEvent.click(screen.getByRole('button', { name: 'Lưu khoản chi' }));
  await screen.findByText('Mất phản hồi');
  expect(onClose).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole('button', { name: 'Lưu khoản chi' }));
  await waitFor(() => expect(create).toHaveBeenCalledTimes(2));
  expect(create.mock.calls[0][0]).toMatchObject({ tripId: 10, costGroup: 'DRIVER_ROAD', driverCostType: 'TOLL', expenseTypeCode: 'TOLL', feeName: 'Vé qua trạm', amount: 80000, customerChargeAmount: 0, payerKind: 'COMPANY' });
  expect(create.mock.calls[1][1]).toBe(create.mock.calls[0][1]);
});
