/**
 * dispatch-planning facade — re-exports the split modules so every importer
 * (routes/shipments, routes/trips, seed, tests) keeps its existing path.
 * Structure-only split; no behavior change. Named re-exports (not `export *`)
 * so the material-write-registry scanner can follow the chain to the module
 * that declares each durable command.
 */
export { CUSTOMER_OPERATIONAL_NAME, DEFAULT_DISPATCH_HANDOFF_STATUSES, DEFAULT_ROUTE_SERVICE_BUFFER_MINUTES, DEFAULT_ROUTE_SERVICE_SPEED_KPH, DISPATCH_BUSINESS_TIME_ZONE, INTERNAL_FLEET_CARRIER_NAME, LIVE_TRIP_RETURNING, ROUTE_OPERATIONAL_NAME, SITE_OPERATIONAL_NAME, TRAILER_CAPACITY_KG, accountantCustomerScopeIds, addCalendarDays, assertDispatchActor, assertDispatchReadActor, authoritativeCargoWeightKg, buildNotificationPayload, buildPattern, decodeCursorPayload, dispatchAssignmentChanged, dispatchDetailTransportDateSql, dispatchEffectiveRouteIdSql, encodeCursorPayload, encodeDescendingIdCursor, encodeFleetCursor, hasExplicitNotificationTarget, inferTrailerTypeFromContainerCode, inferredVehicleCapacityKg, loadDeclarationNumbers, loadPickupSites, normalizeDate, normalizeDispatchHandoffStatuses, normalizeLimit, parseCursor, parseFleetCursor, parseIsoWithZone, redactDispatchSiteForAccountant, requireAccountantDispatchScope, routeServiceDurationMinutes, shipmentQSearchPredicate, sumSelectedStatusCounts, toFrozenSiteSummary, toIsoOrNull, trimBounded, unaccentedIlike, unaccentedIlikeLike } from './dispatch-planning-utils.service';
export type { DispatchActor, DispatchCursorScope, DispatchFleetCursorPayload, DispatchFleetResource, DispatchHandoffStatus, DispatchListCursorPayload, DispatchQueueStatus, LiveTripRow, Tx } from './dispatch-planning-utils.service';
export { buildZoneTruckSuggestions, listDispatchFleet, listDispatchHandoffs, listDispatchQueue } from './dispatch-planning-queries.service';
export type { ListDispatchFleetInput, ListDispatchHandoffsInput, ListDispatchQueueInput } from './dispatch-planning-queries.service';
export { DISPATCH_DETAIL_PLAN_CARRIER_TYPES, acceptDispatchHandoff, assertResourceAvailability, completeExternalCarrierDispatchOrder, issueFulfillmentDispatchOrder, issueOrderCreateOrUpdate, loadLiveTripForFulfillment, reassignIssuedDispatchWriteCommand, replaceTripContainersForFulfillment } from './dispatch-planning-commands.service';
export type { AcceptDispatchHandoffInput, CompleteExternalCarrierDispatchOrderInput, IssueFulfillmentDispatchOrderInput, IssueOrderMutationResult } from './dispatch-planning-commands.service';
export { assignFulfillmentCarrierInTx, assignFulfillmentCarrierWriteCommand, assignFulfillmentPlate, assignFulfillmentPlateInTx, dispatchDetailDisplayHour, dispatchDetailPriorityOrderSql, dispatchDetailRunMinutesSql, listDispatchDeliveryPointFacets, listDispatchDetailPlanRows, listDispatchPortFacets, listZonePortFacets, listZoneTruckPresence, normalizeFreeTextPlate, normalizeIdList, normalizeTimeMinutes, recomputeLotFullyPlated, requireDispatchZone, resolveDispatchVehicleAssignment, updateDispatchDetailPlan, updateDispatchDetailPlanInTx, updateFulfillmentEstimates } from './dispatch-planning-detail-plan.service';
export type { AssignFulfillmentCarrierInput, AssignFulfillmentPlateInput, CarrierMutationResult, DispatchDetailPlanMutationResult, DispatchVehicleResolution, FulfillmentEstimatesMutationResult, ListDispatchDetailPlanRowsInput, PlateMutationResult, UpdateDispatchDetailPlanInput, UpdateFulfillmentEstimatesInput, ZoneTruckPresenceEvidence, ZoneTruckPresenceItem } from './dispatch-planning-detail-plan.service';
