/**
 * Semantic target resolver for the agent highlight spotlight.
 *
 * The agent directive bridge spotlights elements by a stable string `targetId`.
 * This resolver formalizes a single lookup with a precedence:
 *
 *   1. `[data-tour-id="<targetId>"]`  — the convention for targets whose `id`
 *      is generated by a list renderer.
 *   2. `[id="<targetId>"]`             — stable DOM ids (`trip-new-submit`,
 *      `fuel-save-config-button`, …).
 *   3. `null`                          — target absent.
 *
 * Decision D3: support BOTH selectors — no migration of existing ids.
 */

/**
 * Resolve a target synchronously by `data-tour-id` then `id`. Returns `null`
 * if absent.
 */
export function resolveTourTarget(targetId: string): HTMLElement | null {
  if (!targetId) return null;
  const byDataAttr = document.querySelector<HTMLElement>(
    `[data-tour-id="${cssEscape(targetId)}"]`,
  );
  if (byDataAttr) return byDataAttr;
  // `getElementById` is faster than a querySelector for the id case and does
  // not require escaping — prefer it for the fallback.
  return document.getElementById(targetId) as HTMLElement | null;
}

/** Wrapper so an id with CSS meta-characters is still matched literally. */
function cssEscape(value: string): string {
  if (typeof CSS !== 'undefined' && typeof CSS.escape === 'function') {
    return CSS.escape(value);
  }
  // Fallback: escape characters that are special in an attribute selector.
  return value.replace(/["\\\]]/g, '\\$&');
}
