/**
 * Semantic tour-target resolver (Phase 2).
 *
 * Tours spotlight elements by a stable string `targetId`. Historically the
 * spotlight resolved targets via raw `document.getElementById(targetId)`, which
 * works for the existing stable DOM `id`s (`trip-new-submit`,
 * `fuel-save-config-button`, …) but couples tours to React-generated id space
 * for any new target.
 *
 * This resolver formalizes a single lookup with a precedence:
 *
 *   1. `[data-tour-id="<targetId>"]`  — the convention for NEW targets and for
 *      elements whose `id` is generated by a list renderer.
 *   2. `[id="<targetId>"]`             — the existing stable ids, kept as-is
 *      (migrating them would be churn with no benefit and risk breaking
 *      `?focus=` deep links + tests).
 *   3. `null`                          — target absent.
 *
 * `waitForTourTarget` polls until the element is mounted AND visible
 * (`offsetParent !== null`, with a `getBoundingClientRect` fallback for
 * `position: fixed` elements), returning `null` on timeout — the caller (Phase
 * 3's missing-target recovery UX) renders a skip/retry panel. It never throws,
 * so call sites need no try/catch.
 *
 * Decision D3: support BOTH selectors — no migration of existing ids.
 */

/**
 * Resolve a tour target synchronously. Returns `null` if absent or (for the
 * visibility-checked variant) hidden. Selector precedence: data-tour-id → id.
 */
export function resolveTourTarget(targetId: string): HTMLElement | null {
  if (!targetId) return null;
  const byDataAttr = document.querySelector<HTMLElement>(
    `[data-tour-id="${cssEscape(targetId)}"]`,
  );
  if (byDataAttr) return byDataAttr;
  // `getElementById` is faster than a querySelector for the id case and does
  // not require escaping — prefer it for the fallback.
  return document.getElementById(targetId) as HTMLElement | null;
}

/**
 * Is an element currently visible?
 *
 * Uses NEGATIVE signals (explicit hidden markers) rather than requiring positive
 * layout signals, so it works in both real browsers AND test environments that
 * don't compute layout (jsdom, where `offsetParent` is always null and
 * `getBoundingClientRect()` returns zeros). This also correctly treats
 * `position: fixed` elements (which report `offsetParent === null` even when
 * visible) as visible.
 *
 * Hidden when: the element (or an ancestor) carries `display: none`,
 * `visibility: hidden`, the `hidden` attribute, or is detached from the DOM.
 */
function isVisible(el: HTMLElement): boolean {
  // Fast positive signal: a non-null offsetParent proves layout placed it.
  if (el.offsetParent !== null) return true;
  // Detached — not visible.
  if (!el.isConnected) return false;
  // Walk up checking for explicit hidden markers.
  let node: HTMLElement | null = el;
  while (node) {
    const style = node.style;
    if (style.display === 'none') return false;
    if (style.visibility === 'hidden') return false;
    if (node.hidden) return false;
    node = node.parentElement;
  }
  // No explicit hidden marker → treat as visible. Covers `position: fixed`
  // (real browsers) and any element in jsdom (which lacks layout).
  return true;
}

/**
 * Poll `resolveTourTarget` until the element mounts and is visible, or the
 * timeout elapses. Returns the element, or `null` on timeout (NEVER throws).
 *
 * @param targetId  stable tour target id
 * @param timeoutMs default 10_000ms; pass 0 to poll once (no waiting)
 */
export function waitForTourTarget(
  targetId: string,
  opts: { timeoutMs?: number } = {},
): Promise<HTMLElement | null> {
  const timeoutMs = opts.timeoutMs ?? 10_000;
  return new Promise((resolve) => {
    // Fast path: already present.
    const first = resolveTourTarget(targetId);
    if (first && isVisible(first)) return resolve(first);

    if (timeoutMs <= 0) return resolve(null);

    const deadline = Date.now() + timeoutMs;
    const interval = 100;
    const attempt = () => {
      const el = resolveTourTarget(targetId);
      if (el && isVisible(el)) return resolve(el);
      if (Date.now() >= deadline) return resolve(null);
      window.setTimeout(attempt, interval);
    };
    window.setTimeout(attempt, interval);
  });
}

/** Wrapper so an id with CSS meta-characters is still matched literally. */
function cssEscape(value: string): string {
  if (typeof CSS !== 'undefined' && typeof CSS.escape === 'function') {
    return CSS.escape(value);
  }
  // Fallback: escape characters that are special in an attribute selector.
  return value.replace(/["\\\]]/g, '\\$&');
}
